### ISSUE TITLE
PowerShell: 2.7.1149 fails when debugging locally.

### ISSUE THREAD

**Issue by mgeorgebrown89** [Azure/azure-functions-core-tools#1288] opened 2019-05-07 19:15 UTC
My PowerShell function app was working fine yesterday, today I got these errors after running it:

```
The module 'Microsoft.PowerShell.Utility' could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Utility'.
At line:0 char:0
```
```
Debug-Runspace : The term 'Debug-Runspace' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Debug-Runspace -Id 1
+ ~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Debug-Runspace:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
When I first set everything up, I got these errors, but I found a temporary workaround by installing a previous version of Core Tools. I did that again just now, (version 2.6.1080) and it seems to be working again.

**Comment by TylerLeonhardt** [comment] 2019-05-14 23:45
This was caused by a regression that was fixed and released. @mgeorgebrown89 confirmed it so we can close this issue.

**Comment by ahmedelnably** [comment] 2019-05-15 16:40
Closing as the fix got released

**Closed by ahmedelnably** 2019-05-15 16:40 UTC
