### ISSUE TITLE
NPM show 2.7.3188 as latest

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#2665] opened 2021-07-27 06:47 UTC
NPM show 2.7.3188 as latest version. I assume it should be corrected to 3.0.3568

![image](https://user-images.githubusercontent.com/57396/127108487-a9008ca4-e3d6-4ff4-9a72-a6f5390ef08d.png)

**Comment by anthonychu** [comment] 2021-07-29 18:16
@fabiocav @apawast Can we consider pointing latest to the latest stable version? I know in the past we didn't do this because it's a breaking change for CI processes that might install it without a version number. But this is causing customers to install older versions. This is not how most people expect npm packages to work.

**Comment by anthonychu** [comment] 2021-07-29 18:33
closing as duplicate of #2655

**Closed by anthonychu** 2021-07-29 18:33 UTC
Labels: Needs: Triage :mag:
