### ISSUE TITLE
func extensions install overwrites existing extensions

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-core-tools#728] opened 2018-09-18 21:02 UTC
When using Azure Functions Core Tools version 2.0.1-beta.39 and trying to update extension versions using `func extensions install`, the command overwrites existing installed extensions in extensions.csproj.

Example:

```
func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 1.6.1
```

 results in extensions.csproj's package references looking like this:

```
<ItemGroup>
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.6.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1" />
</ItemGroup>
```

After a subsequent 

```
func extensions install -p Microsoft.Azure.WebJobs.Extensions.Twilio -v 3.0.0-beta8
```

 extensions.csproj's package references look like this:

```
<ItemGroup>
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Twilio" Version="3.0.0-beta8" />
<PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1" />
</ItemGroup>
```

**Comment by ahmelsayed** [comment] 2018-09-18 21:42
@soninaren this is caused by this change https://github.com/Azure/azure-functions-core-tools/commit/5f3d4379293255ea12aae840ecd960aa25617018 

Looks like you're explicitly deleting `extensions.csproj` every time `func extensions install` runs. Was that intitional?

**Comment by soninaren** [comment] 2018-09-18 21:51
This change was intentional, i tested extensively with `func extensions install` missed individual extension installation scenario.
The change was temporary, only for the release 2.0.1-beta.39. The change was made because we had renamed servicebus extensions package, the only way to reliably update the service bus extension was to re-create it extensions.csproj on install command.

**Comment by soninaren** [comment] 2018-09-19 20:56
Fixed in this commit
https://github.com/Azure/azure-functions-core-tools/commit/aba587c7056359038c6a276bde0ba8af97c8f763

**Closed by soninaren** 2018-09-19 20:56 UTC
Labels: bug
