### ISSUE TITLE
Automate apt-get publish step

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-core-tools#2286] opened 2020-10-30 18:12 UTC
We need to automate the apt-get publishing step in our release process

Related to #1684 and #1859

**Comment by apawast** [comment] 2022-08-25 17:48
Closing this as a duplicate of [#1684](https://github.com/Azure/azure-functions-core-tools/issues/1684)

**Closed by apawast** 2022-08-25 17:48 UTC
Labels: P1
