### ISSUE TITLE
Implement SquashFS packaging for publishing to Linux

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1149] opened 2019-03-25 16:43 UTC
Details TBD. @ankitkumarr @ahmelsayed

**Comment by ahmedelnably** [comment] 2019-03-25 17:54
cc/ @fabiocav

**Comment by ahmedelnably** [comment] 2019-04-30 18:03
duplicate of https://github.com/Azure/azure-functions-core-tools/issues/1264

**Closed by ahmedelnably** 2019-04-30 18:03 UTC
Labels: P0, blocked, language:Python, milestone:GA
