### ISSUE TITLE
Blank value in local settings ignored

### ISSUE THREAD

**Issue by hisuwh** [Azure/azure-functions-core-tools#1258] opened 2019-04-08 08:55 UTC
I have a value in my settings `QueuePrefix` which I'm using to prefix my queue names so I can test against different environments locally.

I'm using this in my queue triggers locally: 
```csharp
public static Task Run([QueueTrigger("%QueuePrefix%my-queue-name", Connection = "Storage")] ...
```

This was working so I could test one environment without a prefix and one with.  I'm not sure what has changed (possibly since updating to V2) but this no longer seems to work with blank values.

I get this misleading error when I start the functions app:

```
Skipping 'QueuePrefix' from local settings as it's already defined in current environment variables.
```

And then the following error when it tries to index my function:
```
[08/04/2019 08:45:15] Error indexing method 'MyFunction'
[08/04/2019 08:45:15] Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction'. Microsoft.Azure.WebJobs.Host: '%QueuePrefix%' does not resolve to a value.
```

**Comment by paulbatum** [comment] 2019-04-29 18:27
Thanks for the report, I was able to repro this fairly easily. Good call out about the `Skipping 'QueuePrefix' from local settings as it's already defined in current environment variables.` error, I believe thats the root of the problem. That seems to be caused by the `!string.IsNullOrEmpty(secret.Value)` check in this code:

https://github.com/Azure/azure-functions-core-tools/blob/acc8e0613788d7f2e8b91dd4a1c3628b990a90a9/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L198-L213

@ankitkumarr @ahmelsayed I think this check should only be for null, not for empty. Do you agree?

**Comment by paulbatum** [comment] 2019-04-29 18:30
Forgot to include the details of my repro. All I did was use the V2 queue trigger template, with these two changes:

```csharp
public static void Run([QueueTrigger("%queueprefix%myqueue-items", Connection = "")]string myQueueItem, ILogger log)
```
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "queueprefix": "",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

**Comment by paulbatum** [comment] 2019-04-30 02:30
I tested in azure, and all of this seems to work fine there (the blank prefix is correctly used). So that makes me more convinced this is a core tools specific issue.

**Comment by hisuwh** [comment] 2019-04-30 08:36
@paulbatum this is not working for me in Azure either

**Comment by hisuwh** [comment] 2019-05-01 09:05
Any idea when the fix is likely to be published?

**Comment by hisuwh** [comment] 2019-05-09 09:21
Any update on when this might be available?  I'm unable to develop functions locally because of this currently

**Comment by paulbatum** [comment] 2019-05-10 20:15
@hisuwh I believe the fix is in https://github.com/Azure/azure-functions-core-tools/releases/tag/2.7.1158. Visual Studio and VS code should be pulling this update. Perhaps try restarting your development environment.

**Comment by hisuwh** [comment] 2019-05-14 15:24
@paulbatum restarted my PC.  Running these versions:

```
Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0
```

Still seeing these errors:
![image](https://user-images.githubusercontent.com/4470351/57710346-ac3d0c80-7664-11e9-8b00-157b44cef404.png)

**Comment by ahmelsayed** [comment] 2019-05-14 19:16
the core-tools calls 

```csharp

```

however looking at the code for [`SetEnvironmentVariable()`](https://github.com/dotnet/corefx/blob/b86783ef9525f22b0576278939264897464f9bbd/src/Common/src/CoreLib/System/Environment.cs#L193-L212) it seems that it explicitly treats empty string as a delete operation. Also apparently documented here https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netframework-4.8

**Comment by ahmelsayed** [comment] 2019-05-14 19:16
the core-tools calls 

```csharp
Environment.SetEnvironmentVariable()
```

however looking at the code for [`SetEnvironmentVariable()`](https://github.com/dotnet/corefx/blob/b86783ef9525f22b0576278939264897464f9bbd/src/Common/src/CoreLib/System/Environment.cs#L193-L212) it seems that it explicitly treats empty string as a delete operation. Also apparently documented here https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netframework-4.8

**Comment by ahmelsayed** [comment] 2019-05-14 19:17
I think to handle this correctly I'll need to P/Invoke the right OS call for that to bypass .NET semantics for this....

**Comment by paulbatum** [comment] 2019-05-15 01:26
Ugh, I am not sure of a good way of doing this. If you take an OS call approach you'd have to make sure its handled correctly for each OS.

**Comment by hisuwh** [comment] 2019-06-05 15:07
Any update on this.  This is severely hampering our local testing

**Comment by ahmelsayed** [comment] 2019-06-07 23:08
Sorry for the delay Henry. It's trickier than I expected. There is no way to achieve this on Unix from .NET. On Windows it's straightforward. 

```cs
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool SetEnvironmentVariable(string lpName, string lpValue);

static void Main(string[] args)
{
    SetEnvironmentVariable("emptyEnv", "");
    Console.WriteLine(Environment.GetEnvironmentVariable("emptyEnv") == ""); // true
}
```


on Linux/Mac the libc `setenv()` equivalent doesn't work because .NET operates on a snapshot of the environment from process start, so `setenv()/getenv()` version diversions from what .NET thinks the env is. The only solution for linux/mac would be to relaunch the process with the environment set correctly. are you using Windows?

**Comment by hisuwh** [comment] 2019-06-10 09:14
@ahmelsayed I am using windows. is there a fix for this going to be rolled out to windows then?

**Closed** 2019-06-17 18:02 UTC
