### ISSUE TITLE
Azure Functions Core Tools v4 unable deploy to Kubernetes

### ISSUE THREAD

**Issue by anjithk99hallmark** [Azure/azure-functions-core-tools#3307] opened 2023-03-09 09:47 UTC
Hi Team,

 Please be informed that i have created a function app with dotnet isolated version and pushed the image to ACR, now the image is working in local when we pull that image from ACR and run that through postman. When we wanted to Generate manifest file and deploy the image in AKS. I'm getting only secrets 

data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0LWlzb2xhdGVk
apiVersion: v1
kind: Secret
metadata:
  name: funapp2

 The below command, is not generating the required manifest file with the service, secrets, load balancer. Is there any help that can provided for this ticket.

func kubernetes deploy --name funapp2 --service-type NodePort --image-name willh/funapp2 --dry-run

**Comment by anjithk99hallmark** [comment] 2023-03-09 09:48
#2825  This is the exact issue i'm facing now along #3000

**Comment by apawast** [comment] 2023-03-14 14:12
Hi @anjithk99hallmark, thank you for opening this issue. This is a known issue and we are actively working on it. Duplicate of #2825

**Closed** 2023-03-14 14:12 UTC
Labels: Needs: Triage :mag:
