### ISSUE TITLE
functionapp publish failing to find function app

### ISSUE THREAD

**Issue by jsnikhil** [Azure/azure-functions-core-tools#809] opened 2018-10-16 16:21 UTC
I am trying to deploy to a function app which I have already created via the portal, however the deploy command is failing to find it

```
$ func azure functionapp publish dca4-extract-dimensions
> az account get-access-token --query "accessToken"
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions/<sub1>/resources?api-version=2014-04-01&$filter=(name eq 'dca4-extract-dimensions' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/subscriptions/<sub2>/resources?api-version=2014-04-01&$filter=(name eq 'dca4-extract-dimensions' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/subscriptions/<sub3>/resources?api-version=2014-04-01&$filter=(name eq 'dca4-extract-dimensions' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/subscriptions/<sub4>/resources?api-version=2014-04-01&$filter=(name eq 'dca4-extract-dimensions' and resourceType eq 'Microsoft.Web/sites')
Azure.Functions.Cli.Arm.ArmResourceNotFoundException: Can't find app with name "dca4-extract-dimensions"
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken)
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync()
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container)

$ func --version
2.0.3
```

The function app clearly exists in <sub4> which I have verified by directly calling.

```
https://management.azure.com/subscriptions/<sub4>/resources?api-version=2014-04-01&$filter=(name eq 'dca4-extract-dimensions' and resourceType eq 'Microsoft.Web/sites')
```

The above call did not directly return the result but gave instead a `nextLink`, which when called gave me this result

```
{
    "value": [
        {
            "id": "/subscriptions/<sub4>/resourceGroups/<resource-grup-name>/providers/Microsoft.Web/sites/dca4-extract-dimensions",
            "name": "dca4-extract-dimensions",
            "type": "Microsoft.Web/sites",
            "kind": "functionapp",
            "location": <location>
        }
    ]
}
```

**Comment by ankitkumarr** [comment] 2018-10-18 00:33
Hi @jsnikhil,

This sounds like a duplicate of #738, which was fixed a little back and should be available in the next release.
Let us know if the problem persists after the new version.

**Closed by ankitkumarr** 2018-10-18 00:33 UTC
