### ISSUE TITLE
VS2022 ver.17.11.4 - Debug FunctionApp .NET8 - An error occurred while running CoreToolsHost.System.Text.Json.JsonReaderException

### ISSUE THREAD

**Issue by ripamontigiorgio** [Azure/azure-functions-core-tools#3856] opened 2024-10-02 13:15 UTC
### Version

4.90-inprocess

### Description

With 4.90-inprocess version i receive this error while starting debug a Function App running on .NET8
![image](https://github.com/user-attachments/assets/9e9e1306-fb15-41d8-b7c9-379a6a7ec9c0)

The problem is related to this file "<user>\AppData\Local\AzureFunctionsTools\Releases\4.90.0-inprocess\cli_x64\func.exe".
Copying the func.exe from 4.89 folder resolve, at the moment, the problem. 

### Steps to reproduce

Use VS2022 and try to debug a Function App wiht .NET8 inprocess

**Comment by izodmungo** [comment] 2024-10-03 14:35
+1

Different symptom same fix.

```
[2024-10-03T14:19:47.582Z] Error configuring services in an external startup class.
[2024-10-03T14:19:47.584Z] Error configuring services in an external startup class. : Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
[2024-10-03T14:19:47.617Z] A host error has occurred during startup operation '15e70146-e57f-4a11-af78-fe7ed653bd86'.
[2024-10-03T14:19:47.619Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. : Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
```

The directory at `%userprofile%\appdata\Local\AzureFunctionsTools\Releases\4.90.0-inprocess\cli_x64` wasn't bare but appears to be missing most of the required files. Bad deploy of 4.90.0-inprocess? 

Another dev on my team got OP's error due to comments in local.settings.json removing and got the error I was seeing.

**Comment by Skymogul** [comment] 2024-10-03 16:28
We are experiencing a variation of this issue. When debugging a .Net 8 in-process function in Visual Studio, it appears to call `func.exe` from the `in-proc6` folder instead of the `in-proc8` folder, resulting in the same error. If we rename `in-proc8` to `in-proc6` it works as expected.

**Comment by tiwilson7** [comment] 2024-10-03 16:31
+1

We are experiencing both of the issues above and found the same workaround after a lot of banging our heads against the desk.

We are using Rider primarily but also experience the issue in Visual Studio. Using "--verbose" in Rider we can see that the inproc6 host is being selected instead of inproc8.

For Rider, I cloned C:\Users\[username\\.AzureToolsForIntelliJ\AzureFunctionsCoreTools\v0\4.90.0-inprocess\in-proc8 and renamed it to in-proc6 to work around the issue.

![image](https://github.com/user-attachments/assets/04db0dc5-a0f3-4d86-b0aa-bdbdd67f1306)

**Comment by JonathanBedrava** [comment] 2024-10-03 16:42
+1

We too are experiencing the issues above and have made use of the work around posted above.

**Comment by JackRailtown** [comment] 2024-10-03 18:58
We are also affected by this issue the above workaround doesnt seem to have worked here

**Comment by qasimalik786** [comment] 2024-10-03 20:05
We are experiencing different issues. Any workaround? 
![image](https://github.com/user-attachments/assets/216de264-f868-4bd4-8232-d47c32532bab)

**Comment by seancolonello** [comment] 2024-10-03 22:34
For me, the workaround was to copy the entire cli_x64 folder from \4.89.0-inprocess to \4.90.0-inprocess (not just func.exe as the original workaround suggests).

**Comment by nicoedg** [comment] 2024-10-04 10:25
> For me, the workaround was to copy the entire cli_x64 folder from \4.89.0-inprocess to \4.90.0-inprocess (not just func.exe as the original workaround suggests).

Where I can find the 4.89.0-inprocess?

**Comment by seancolonello** [comment] 2024-10-04 13:30
> > For me, the workaround was to copy the entire cli_x64 folder from \4.89.0-inprocess to \4.90.0-inprocess (not just func.exe as the original workaround suggests).
> 
> Where I can find the 4.89.0-inprocess?

%userprofile%\appdata\Local\AzureFunctionsTools\Releases\

**Comment by vpaul-dm** [comment] 2024-10-04 14:28
My workaround was to open the manifest json file in the 4.90 folder and update all the file paths from 4.90 to 4.89.

**Comment by mattchenderson** [comment] 2024-10-05 01:32
Hi all - We're working on a release that will address some of the issues captured in a new version. I'll take some tactical steps to get the previous version restored on latest (as 91-inprocess) in advance of then.

There are a few issues I see reflected here:
1. @ripamontigiorgio's issue looks to be related to issues in parsing the `local.settings.json` file. Indeed, it seems like this is an issue of comments being included. Removal of those comments should be a fine workaround for the moment. If comments were tolerated by 89 and earlier, I'd like to have this issue ultimately track that work specifically, as it if the OP concern (pending confirmation).
1. https://github.com/Azure/azure-functions-core-tools/issues/3858 (also reflected in this thread) is when there is trouble locating `local.settings.json` or getting the `Values` object out of it.
1. @izodmungo's issue looks to me to be .NET 6 being loaded even though their project is .NET 8. That seems to align with what @tiwilson7 is seeing more explicitly. I have some follow-up questions for y'all below to make sure we have the right repro steps.
1. Not reported in this thread, but observed by our team when explicitly forcing VS to take the .NET 6 path through the root func.exe: there was a memory error when the debugger is attached, but only on specific hardware. I would not expect anyone here to take that exact path, but it could theoretically appear for folks hitting that third case. This is resolved for the next version.

In general, issues with `local.settings.json` should be addressed in the forthcoming new 92-inprocess version. What you see with 90-inprocess throws weirdly, but in what is _currently_ planned for 92-inprocess, these would instead attempt to load the .NET 6 version. .NET 6 is treated as the default, and moving to .NET 8 requires all of the following to be true:
- `local.settings.json` is present and contains `FUNCTIONS_WORKER_RUNTIME` set to "dotnet"
- `local.settings.json` is present and contains `FUNCTIONS_INPROC_NET8_ENABLED` set to "1"
[Here's the doc reference for that.](https://learn.microsoft.com/azure/azure-functions/functions-dotnet-class-library#updating-to-target-net-8)

If those conditions are not met exactly, .NET 6 being loaded is expected. However, I gather that there is still a problem where that selection was happening incorrectly for folks experiencing the third issue. For this, I would like to understand the project setup better, including the structure of `local.settings.json` and confirmation of if the above criteria were set or not. Please **do not** share the contents of that file here unredacted, as we do not wish for you to disclose any secrets, etc. However, any sanitized details you can provide about this setup would be useful. Please share those in reply to https://github.com/Azure/azure-functions-core-tools/issues/3864. That will help us better keep track of each repair item that's needed here.

The workarounds described of editing the manifest or copying the files over should address the versioning IF you still have an older version present. By default, they are not removed by VS at least. New installs of your IDE of choice may have an older cached version but pull down the latest (currently 90), so 89 specifically may not be available.

Thanks all, for reporting this, and for helping each other with workaround steps. We'll get this sorted. I'll report back once I have the previous version restored as latest.

**Comment by xin9le** [comment] 2024-10-05 13:47
@mattchenderson 

I encountered a similar issue. I was able to circumvent the problem by removing comments from the `local.settings.json` file. Based on the exception stack trace, it appears that the cause lies in the newly established `LocalSettingsJsonParser` from #3831. A potential quick solution might be to provide the `JsonCommentHandling.Skip` option to `JsonDocument.Parse()`, which could potentially mitigate the issue.

- https://github.com/Azure/azure-functions-core-tools/pull/3831/files#diff-c8e9c9dfc9a890eb0f8b8087e898852c0c4f7a01d680aae8d527bed01262e89dR26

Furthermore, the `FUNCTIONS_INPROC_NET8_ENABLED` setting no longer accepts numerical values, as demonstrated below. This seems to be due to the use of `JsonElement.GetString()`:

```json
"FUNCTIONS_INPROC_NET8_ENABLED": 1  // Currently, not acceptable (This was not problematic previously)
"FUNCTIONS_INPROC_NET8_ENABLED": "1"  // Acceptable
```

- https://github.com/Azure/azure-functions-core-tools/pull/3831/files#diff-ba032e2442a877ac51605470a5baaf14ecd8f231f5185f1748de1aa88c2acfe3R42

I hope this information proves helpful for your consideration.

**Comment by nicoedg** [comment] 2024-10-07 07:19
I had the same problem.
I was debugging my function and after a sequence of start and stop the console returns this error.
I read all your comments and based my troubleshooting on a problem in Azure Function Tools (AFT).
But after many attempts, I tried to create a new solution, I ran the debugger and to my surprise it works.
So the problem was not AFT, but my solution.
So I excluded all functions but one from the project and cleaned all settings from my local.settings.json and debugged the project... it runs.
Then I added all the functions one by one with their associated settings to local.settings.json and debugged at each addition.
Now my solution is perfectly debuggable and my code has not been changed.
I don't know why AFT was stuck in that state, but my workaround was to exclude and re-include the functions one by one with a run of AFT after each addition.

**Comment by izodmungo** [comment] 2024-10-07 14:15
@mattchenderson

I reset the 4.90.0-inprocess folder and added "FUNCTIONS_INPROC_NET8_ENABLED": "1" to local.settings.json. This is working for me now. We recently updated this project from .Net 6 to 8 and must have missed that change to the settings file.

Thanks for for the help.

**Comment by mattchenderson** [comment] 2024-10-07 15:57
91-inprocess should now start showing up - this is basically the same as 89-inprocess.

For VS, this should be fetched upon launching a Functions project, but you can force it to check for updates:

1. Navigate to *Tools* > **Options**, choose Azure Functions under **Projects and Solutions**.
2. Select **Check for updates** and install updates as prompted.

**Comment by drdamour** [comment] 2024-10-07 18:25
@mattchenderson will 91-inprocess allow trailing commas like prior version did too? cf https://github.com/Azure/azure-functions-core-tools/pull/3866/files#r1790686955

**Comment by mattchenderson** [comment] 2024-10-11 00:40
Hi all - we are now pushing the next version (the `4.92.0-inprocess` version). This reintroduces the payload that prompted this thread, but with a series of fixes based on your reports. Thank you again for helping us flag these issues!

We would love explicit confirmation that with these changes in place, things continue to work for your scenarios. If you could please try out the latest version and confirm with a reply in this thread, that would help a ton. We'll keep this issue open for a bit just in case anything comes up, but we'll plan to close it out in the absence of any concerns.

**Comment by xin9le** [comment] 2024-10-11 04:18
@mattchenderson 
I have tested this in my environment, and it appears that the aforementioned issues have been resolved. I would like to express my gratitude for your prompt attention to this matter 👍

**Comment by mattchenderson** [comment] 2024-10-15 01:26
Hi all - we'll proceed to close this issue as we believe things to be resolved with the newer versions. If you encounter any other problems, please let us know through a new issue. Again, thanks for the reports here!

**Closed by mattchenderson** 2024-10-15 01:26 UTC
Labels: bug, area: host-split
