### ISSUE TITLE
Cannot create directory for shared memory usage: /dev/shm/AzureFunctions [M1 Pro Max Apple]

### ISSUE THREAD

**Issue by geg00** [Azure/azure-functions-core-tools#2828] opened 2021-11-10 23:21 UTC
> Executing task: . .venv/bin/activate && func host start <

Found Python version 3.9.7 (python3).

Azure Functions Core Tools
Core Tools Version:       4.0.3780 Commit hash: 2b9e0e618f69993ff119009e48587b67ac85450e  (64-bit)
Function Runtime Version: 4.0.0.16394

[2021-11-10T23:15:07.679Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-11-10T23:15:07.689Z] System.Private.CoreLib: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.

This is just out of the box sample from the website.
https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-python-vscode

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7429.41.5
  OS Loader Version:	7429.41.5
  

python --version
Python 3.9.7

(.venv) gerardogarcia@Gerardos-MacBook-Pro hello3 % func host start --verbose
Found Python version 3.9.7 (python3).

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools
Core Tools Version:       4.0.3780 Commit hash: 2b9e0e618f69993ff119009e48587b67ac85450e  (64-bit)
Function Runtime Version: 4.0.0.16394

[2021-11-10T23:29:45.772Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-11-10T23:29:45.774Z] System.Private.CoreLib: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
[2021-11-10T23:29:45.883Z] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '6f0b6585-cc49-4067-87e9-5f591cf3dbfd'
[2021-11-10T23:29:45.902Z] Reading host configuration file '/Users/gerardogarcia/kd1/hello3/host.json'
[2021-11-10T23:29:45.905Z] Host configuration file read:
[2021-11-10T23:29:45.905Z] {
[2021-11-10T23:29:45.905Z]   "version": "2.0",
[2021-11-10T23:29:45.905Z]   "logging": {
[2021-11-10T23:29:45.905Z]     "applicationInsights": {
[2021-11-10T23:29:45.905Z]       "samplingSettings": {
[2021-11-10T23:29:45.905Z]         "isEnabled": true,
[2021-11-10T23:29:45.905Z]         "excludedTypes": "Request"
[2021-11-10T23:29:45.905Z]       }
[2021-11-10T23:29:45.905Z]     }
[2021-11-10T23:29:45.905Z]   },
[2021-11-10T23:29:45.905Z]   "extensionBundle": {
[2021-11-10T23:29:45.905Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-11-10T23:29:45.905Z]     "version": "[2.*, 3.0.0)"
[2021-11-10T23:29:45.905Z]   }
[2021-11-10T23:29:45.905Z] }
[2021-11-10T23:29:45.926Z] Loading functions metadata
[2021-11-10T23:29:45.967Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:java
[2021-11-10T23:29:45.969Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:powershell
[2021-11-10T23:29:45.970Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:node
[2021-11-10T23:29:45.972Z] Reading functions metadata
[2021-11-10T23:29:45.994Z] 3 functions found
[2021-11-10T23:29:46.009Z] 3 functions loaded
[2021-11-10T23:29:46.019Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /Users/gerardogarcia/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2021-11-10T23:29:46.024Z] Found a matching extension bundle at /Users/gerardogarcia/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/2.8.4
[2021-11-10T23:29:46.025Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2021-11-10T23:29:46.888Z] Skipping bundle download since it already exists at path /Users/gerardogarcia/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/2.8.4
[2021-11-10T23:29:46.898Z] Loading extension bundle from /Users/gerardogarcia/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/2.8.4/bin
[2021-11-10T23:29:46.914Z] Loading startup extension 'DurableTask'
[2021-11-10T23:29:47.005Z] Loaded extension 'DurableTask' (2.0.0.0)
[2021-11-10T23:29:47.036Z] Reading host configuration file '/Users/gerardogarcia/kd1/hello3/host.json'
[2021-11-10T23:29:47.036Z] Host configuration file read:
[2021-11-10T23:29:47.036Z] {
[2021-11-10T23:29:47.036Z]   "version": "2.0",
[2021-11-10T23:29:47.036Z]   "logging": {
[2021-11-10T23:29:47.036Z]     "applicationInsights": {
[2021-11-10T23:29:47.036Z]       "samplingSettings": {
[2021-11-10T23:29:47.036Z]         "isEnabled": true,
[2021-11-10T23:29:47.036Z]         "excludedTypes": "Request"
[2021-11-10T23:29:47.036Z]       }
[2021-11-10T23:29:47.036Z]     }
[2021-11-10T23:29:47.036Z]   },
[2021-11-10T23:29:47.036Z]   "extensionBundle": {
[2021-11-10T23:29:47.036Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-11-10T23:29:47.036Z]     "version": "[2.*, 3.0.0)"
[2021-11-10T23:29:47.036Z]   }
[2021-11-10T23:29:47.036Z] }
[2021-11-10T23:29:47.446Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:java
[2021-11-10T23:29:47.448Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:powershell
[2021-11-10T23:29:47.448Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:node
[2021-11-10T23:29:47.670Z] Using the default storage provider: AzureStorage.
[2021-11-10T23:29:48.232Z] Initializing Warmup Extension.
[2021-11-10T23:29:49.368Z] Durable extension configuration loaded: {"httpSettings":{"defaultAsyncRequestSleepTimeMilliseconds":30000},"hubName":"TestHubName","storageProvider":{"connectionStringName":null,"controlQueueBatchSize":32,"partitionCount":4,"controlQueueBufferThreshold":256,"controlQueueVisibilityTimeout":"00:05:00","workItemQueueVisibilityTimeout":"00:05:00","trackingStoreConnectionStringName":null,"trackingStoreNamePrefix":null,"fetchLargeMessagesAutomatically":true,"maxQueuePollingInterval":"00:00:30","useLegacyPartitionManagement":false},"tracing":{"traceInputsAndOutputs":false,"allowVerboseLinuxTelemetry":false,"traceReplayEvents":false,"distributedTracingEnabled":false,"distributedTracingProtocol":"HttpCorrelationProtocol"},"notifications":{"eventGrid":null},"maxConcurrentActivityFunctions":100,"maxConcurrentOrchestratorFunctions":100,"localRpcEndpointEnabled":null,"extendedSessionsEnabled":false,"extendedSessionIdleTimeoutInSeconds":30,"maxOrchestrationActions":100000,"overridableExistingInstanceStates":"NonRunningStates","entityMessageReorderWindowInMinutes":30,"useGracefulShutdown":false,"rollbackEntityOperationsOnExceptions":true,"useAppLease":true,"appLeaseOptions":{"renewInterval":"00:00:25","acquireInterval":"00:05:00","leaseInterval":"00:01:00"}}. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.5.1.
[2021-11-10T23:29:49.408Z] Opened local RPC endpoint: http://127.0.0.1:17071/durabletask/. InstanceId: . Function: . HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.5.1. SequenceNumber: 0.
[2021-11-10T23:29:49.484Z] Initializing Host. OperationId: '6f0b6585-cc49-4067-87e9-5f591cf3dbfd'.
[2021-11-10T23:29:49.495Z] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=6f0b6585-cc49-4067-87e9-5f591cf3dbfd
[2021-11-10T23:29:49.524Z] LoggerFilterOptions
[2021-11-10T23:29:49.524Z] {
[2021-11-10T23:29:49.524Z]   "MinLevel": "None",
[2021-11-10T23:29:49.524Z]   "Rules": [
[2021-11-10T23:29:49.524Z]     {
[2021-11-10T23:29:49.524Z]       "ProviderName": null,
[2021-11-10T23:29:49.524Z]       "CategoryName": null,
[2021-11-10T23:29:49.524Z]       "LogLevel": null,
[2021-11-10T23:29:49.524Z]       "Filter": "<AddFilter>b__0"
[2021-11-10T23:29:49.524Z]     },
[2021-11-10T23:29:49.524Z]     {
[2021-11-10T23:29:49.524Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-11-10T23:29:49.524Z]       "CategoryName": null,
[2021-11-10T23:29:49.524Z]       "LogLevel": "None",
[2021-11-10T23:29:49.524Z]       "Filter": null
[2021-11-10T23:29:49.524Z]     },
[2021-11-10T23:29:49.524Z]     {
[2021-11-10T23:29:49.524Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-11-10T23:29:49.524Z]       "CategoryName": null,
[2021-11-10T23:29:49.525Z]       "LogLevel": null,
[2021-11-10T23:29:49.525Z]       "Filter": "<AddFilter>b__0"
[2021-11-10T23:29:49.525Z]     },
[2021-11-10T23:29:49.525Z]     {
[2021-11-10T23:29:49.525Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2021-11-10T23:29:49.525Z]       "CategoryName": null,
[2021-11-10T23:29:49.525Z]       "LogLevel": null,
[2021-11-10T23:29:49.525Z]       "Filter": "<AddFilter>b__0"
[2021-11-10T23:29:49.525Z]     }
[2021-11-10T23:29:49.525Z]   ]
[2021-11-10T23:29:49.525Z] }
[2021-11-10T23:29:49.525Z] LoggerFilterOptions
[2021-11-10T23:29:49.525Z] {
[2021-11-10T23:29:49.525Z]   "MinLevel": "None",
[2021-11-10T23:29:49.525Z]   "Rules": [
[2021-11-10T23:29:49.525Z]     {
[2021-11-10T23:29:49.525Z]       "ProviderName": null,
[2021-11-10T23:29:49.525Z]       "CategoryName": null,
[2021-11-10T23:29:49.525Z]       "LogLevel": null,
[2021-11-10T23:29:49.525Z]       "Filter": "<AddFilter>b__0"
[2021-11-10T23:29:49.525Z]     },
[2021-11-10T23:29:49.525Z]     {
[2021-11-10T23:29:49.525Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-11-10T23:29:49.525Z]       "CategoryName": null,
[2021-11-10T23:29:49.525Z]       "LogLevel": "None",
[2021-11-10T23:29:49.525Z]       "Filter": null
[2021-11-10T23:29:49.525Z]     },
[2021-11-10T23:29:49.525Z]     {
[2021-11-10T23:29:49.525Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-11-10T23:29:49.525Z]       "CategoryName": null,
[2021-11-10T23:29:49.525Z]       "LogLevel": null,
[2021-11-10T23:29:49.525Z]       "Filter": "<AddFilter>b__0"
[2021-11-10T23:29:49.525Z]     },
[2021-11-10T23:29:49.525Z]     {
[2021-11-10T23:29:49.525Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2021-11-10T23:29:49.525Z]       "CategoryName": null,
[2021-11-10T23:29:49.525Z]       "LogLevel": null,
[2021-11-10T23:29:49.525Z]       "Filter": "<AddFilter>b__0"
[2021-11-10T23:29:49.525Z]     }
[2021-11-10T23:29:49.525Z]   ]
[2021-11-10T23:29:49.525Z] }
[2021-11-10T23:29:49.525Z] ConcurrencyOptions
[2021-11-10T23:29:49.525Z] {
[2021-11-10T23:29:49.525Z]   "DynamicConcurrencyEnabled": false,
[2021-11-10T23:29:49.525Z]   "MaximumFunctionConcurrency": 500,
[2021-11-10T23:29:49.525Z]   "CPUThreshold": 0.8,
[2021-11-10T23:29:49.526Z]   "SnapshotPersistenceEnabled": true
[2021-11-10T23:29:49.526Z] }
[2021-11-10T23:29:49.526Z] FunctionResultAggregatorOptions
[2021-11-10T23:29:49.526Z] {
[2021-11-10T23:29:49.526Z]   "BatchSize": 1000,
[2021-11-10T23:29:49.526Z]   "FlushTimeout": "00:00:30",
[2021-11-10T23:29:49.526Z]   "IsEnabled": true
[2021-11-10T23:29:49.526Z] }
[2021-11-10T23:29:49.526Z] SingletonOptions
[2021-11-10T23:29:49.526Z] {
[2021-11-10T23:29:49.526Z]   "LockPeriod": "00:00:15",
[2021-11-10T23:29:49.526Z]   "ListenerLockPeriod": "00:00:15",
[2021-11-10T23:29:49.526Z]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2021-11-10T23:29:49.526Z]   "LockAcquisitionPollingInterval": "00:00:05",
[2021-11-10T23:29:49.526Z]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2021-11-10T23:29:49.526Z] }
[2021-11-10T23:29:49.528Z] Starting JobHost
[2021-11-10T23:29:49.531Z] Starting Host (HostId=gerardosmacbookpro-1058516915, InstanceId=0df0a273-3685-4cb2-a684-01a7be54e9b7, Version=4.0.0.16394, ProcessId=1358, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2021-11-10T23:29:49.548Z] Loading functions metadata
[2021-11-10T23:29:49.551Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:java
[2021-11-10T23:29:49.551Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:powershell
[2021-11-10T23:29:49.552Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:node
[2021-11-10T23:29:49.563Z] 3 functions loaded
[2021-11-10T23:29:49.631Z] Generating 3 job function(s)
[2021-11-10T23:29:49.779Z] Traceback (most recent call last):
[2021-11-10T23:29:49.781Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 50, in main
[2021-11-10T23:29:49.781Z]     return aio_compat.run(start_async(
[2021-11-10T23:29:49.781Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
[2021-11-10T23:29:49.782Z]     return loop.run_until_complete(main)
[2021-11-10T23:29:49.782Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[2021-11-10T23:29:49.782Z]     return future.result()
[2021-11-10T23:29:49.782Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 58, in start_async
[2021-11-10T23:29:49.782Z]     from . import dispatcher
[2021-11-10T23:29:49.782Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/dispatcher.py", line 19, in <module>
[2021-11-10T23:29:49.782Z]     import grpc
[2021-11-10T23:29:49.782Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/__init__.py", line 23, in <module>
[2021-11-10T23:29:49.782Z]     from grpc._cython import cygrpc as _cygrpc
[2021-11-10T23:29:49.783Z] ImportError: dlopen(/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-39-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-39-darwin.so' (no such file)
[2021-11-10T23:29:49.785Z] Traceback (most recent call last):
[2021-11-10T23:29:49.785Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/worker.py", line 86, in <module>
[2021-11-10T23:29:49.785Z]     main.main()
[2021-11-10T23:29:49.785Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 50, in main
[2021-11-10T23:29:49.785Z]     return aio_compat.run(start_async(
[2021-11-10T23:29:49.785Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
[2021-11-10T23:29:49.785Z]     return loop.run_until_complete(main)
[2021-11-10T23:29:49.785Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[2021-11-10T23:29:49.785Z]     return future.result()
[2021-11-10T23:29:49.785Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 58, in start_async
[2021-11-10T23:29:49.785Z]     from . import dispatcher
[2021-11-10T23:29:49.785Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/dispatcher.py", line 19, in <module>
[2021-11-10T23:29:49.785Z]     import grpc
[2021-11-10T23:29:49.786Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/__init__.py", line 23, in <module>
[2021-11-10T23:29:49.786Z]     from grpc._cython import cygrpc as _cygrpc
[2021-11-10T23:29:49.786Z] ImportError: dlopen(/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-39-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-39-darwin.so' (no such file)
[2021-11-10T23:29:49.833Z] Found the following functions:
[2021-11-10T23:29:49.833Z] Host.Functions.DurableFunctionsHttpStart1
[2021-11-10T23:29:49.834Z] Host.Functions.DurableFunctionsOrchestrator1
[2021-11-10T23:29:49.834Z] Host.Functions.Hello
[2021-11-10T23:29:49.834Z] 
[2021-11-10T23:29:49.860Z] HttpOptions
[2021-11-10T23:29:49.860Z] {
[2021-11-10T23:29:49.860Z]   "DynamicThrottlesEnabled": false,
[2021-11-10T23:29:49.860Z]   "EnableChunkedRequestBinding": false,
[2021-11-10T23:29:49.860Z]   "MaxConcurrentRequests": -1,
[2021-11-10T23:29:49.860Z]   "MaxOutstandingRequests": -1,
[2021-11-10T23:29:49.860Z]   "RoutePrefix": "api"
[2021-11-10T23:29:49.860Z] }
[2021-11-10T23:29:49.868Z] Initializing function HTTP routes
[2021-11-10T23:29:49.868Z] Mapped function route 'api/orchestrators/{functionName}' [post,get] to 'DurableFunctionsHttpStart1'
[2021-11-10T23:29:49.868Z] 
[2021-11-10T23:29:49.877Z] Traceback (most recent call last):
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 50, in main
[2021-11-10T23:29:49.878Z]     return aio_compat.run(start_async(
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
[2021-11-10T23:29:49.878Z]     return loop.run_until_complete(main)
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[2021-11-10T23:29:49.878Z]     return future.result()
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 58, in start_async
[2021-11-10T23:29:49.878Z]     from . import dispatcher
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/dispatcher.py", line 19, in <module>
[2021-11-10T23:29:49.878Z]     import grpc
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/__init__.py", line 23, in <module>
[2021-11-10T23:29:49.878Z]     from grpc._cython import cygrpc as _cygrpc
[2021-11-10T23:29:49.878Z] ImportError: dlopen(/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-39-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-39-darwin.so' (no such file)
[2021-11-10T23:29:49.878Z] Traceback (most recent call last):
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/worker.py", line 86, in <module>
[2021-11-10T23:29:49.878Z]     main.main()
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 50, in main
[2021-11-10T23:29:49.878Z]     return aio_compat.run(start_async(
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
[2021-11-10T23:29:49.878Z]     return loop.run_until_complete(main)
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[2021-11-10T23:29:49.878Z]     return future.result()
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 58, in start_async
[2021-11-10T23:29:49.878Z]     from . import dispatcher
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/azure_functions_worker/dispatcher.py", line 19, in <module>
[2021-11-10T23:29:49.878Z]     import grpc
[2021-11-10T23:29:49.878Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/__init__.py", line 23, in <module>
[2021-11-10T23:29:49.878Z]     from grpc._cython import cygrpc as _cygrpc
[2021-11-10T23:29:49.879Z] ImportError: dlopen(/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.3780/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-39-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-39-darwin.so' (no such file)
[2021-11-10T23:29:49.884Z] Host initialized (335ms)
[2021-11-10T23:29:49.894Z] Starting task hub worker. InstanceId: . Function: . HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.5.1. SequenceNumber: 1.

Functions:

        DurableFunctionsHttpStart1: [POST,GET] http://localhost:7071/api/orchestrators/{functionName}

        DurableFunctionsOrchestrator1: orchestrationTrigger

        Hello: activityTrigger

[2021-11-10T23:29:51.932Z] Task hub worker started. Latency: 00:00:02.0356477. InstanceId: . Function: . HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.5.1. SequenceNumber: 2.
[2021-11-10T23:29:51.941Z] Host started (2406ms)
[2021-11-10T23:29:51.941Z] Job host started
[2021-11-10T23:29:54.930Z] Host lock lease acquired by instance ID '000000000000000000000000C270DC85'.

**Comment by apawast** [comment] 2021-11-10 23:38
@geg00 the fix for this issue should be resolved in functions version 4.03971. Can you please upgrade and see if that fixes it?

**Comment by geg00** [comment] 2021-11-11 00:09
> @geg00 the fix for this issue should be resolved in functions version 4.0.3971. Can you please upgrade and see if that fixes it?

I think I found the file
https://github.com/Azure/azure-functions-core-tools/releases
Can you provide instructions on how to install and overwrite the current preview?

**Comment by ejizba** [comment] 2021-11-11 01:08
The fix has not been released to brew yet, but that should hopefully be soon. To be clear, though, the fix was to remove the errors about "/dev/shm", but you can just ignore those anyways (main issue for this is https://github.com/Azure/azure-functions-core-tools/issues/2600). I think the real reason you're failing to run your app locally is because you are running on an M1 Mac. We have a separate issue tracking that here: https://github.com/Azure/azure-functions-core-tools/issues/2451. There's a few possible workarounds in that thread, but I don't believe we have a true resolution yet.

Closing as duplicate of https://github.com/Azure/azure-functions-core-tools/issues/2451

**Closed by ejizba** 2021-11-11 01:08 UTC
Labels: Needs: Attention :wave:
