### ISSUE TITLE
Latest release link yields a 404 (4.0.6543.zip)

### ISSUE THREAD

**Issue by jasonvangundy** [Azure/azure-functions-core-tools#4156] opened 2024-11-08 22:48 UTC
### Version

4.0.6543

### Description

Suddenly CI builds using the task `FuncToolsInstaller@0` are yielding a `404` when trying to get the latest version.  

The URL structure from a build at `2024-11-08T16:41:39Z`  was: `https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.6280/Azure.Functions.Cli.linux-x64.4.0.6280.zip`, but the artifact now appears to be linked at this URL: 

`https://github.com/Azure/azure-functions-core-tools/releases/download/v4.0.6543/Azure.Functions.Cli.linux-x64.v4.0.6543.zip` - note the `v4.0.6543.zip` vs `4.0.6280.zip`, previously without the `v` and now with it.  

I'm unclear if this is a publishing issue, or a `FuncToolsInstaller` task issue.  Neither project shows a recent release, so it's hard to tell at the moment.

### Steps to reproduce

Hit https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.6280/Azure.Functions.Cli.linux-x64.4.0.6280.zip and download the artifact.

Hit https://github.com/Azure/azure-functions-core-tools/releases/download/v4.0.6543/Azure.Functions.Cli.linux-x64.v4.0.6543.zip and get a 404

**Comment by up2pixy** [comment] 2024-11-08 23:50
We got the same issue. The ADO task is looking for the version in the path and version in the filename as same. Their source code: https://github.com/microsoft/azure-pipelines-tasks/blob/18b2a6e45201b869e5439f15ea32129602b3babf/Tasks/FuncToolsInstallerV0/src/utils.ts#L95C1-L109C2. Please re-release with a path without `v`

**Comment by morten-b** [comment] 2024-11-11 08:36
Path to the old releases follows the same pattern as with the current (failing) one being without the `v` e.g.:
https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.6280/Azure.Functions.Cli.linux-x64.4.0.6280.zip

I would therefore guess that the issue is with the pipeline task

**Comment by aishwaryabh** [comment] 2024-11-11 22:48
This has been fixed now for the latest version (4.0.6549): https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.6594

**Comment by aishwaryabh** [comment] 2024-11-13 21:56
Issue has been resolved

**Closed by aishwaryabh** 2024-11-13 21:56 UTC
Labels: potential-bug
