### ISSUE TITLE
`func new` breaking for .NET Isolated

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-core-tools#3217] opened 2022-12-06 22:00 UTC
On multiple recent versions (tested on Windows and WSL), the basic project setup for .NET Isolated will fail.

```bash
func init --worker-runtime "dotnet-isolated" --target-framework "net7.0"
func new --name "DotNet7Function" --template "HTTP trigger"
```

will yield

```
Restore failed.
Post action failed.

The function "DotNet7Fucntion" was created successfully from the "HTTP trigger" template.
```

with the first two lines as error statements.

The appropriate .NET SDKs and runtimes are available in the test environments. A `dotnet restore` works just fine.

**Comment by fabiocav** [comment] 2022-12-09 00:33
@soninaren this is looking like a problem with the dotnet template.

**Comment by yooakim** [comment] 2022-12-30 08:17
I have the same experiences as reported by @mattchenderson. I have the following SDKs installed:
```
dotnet --list-sdks
6.0.404 [C:\Program Files\dotnet\sdk]
7.0.101 [C:\Program Files\dotnet\sdk]
```
and the function core tools is version 
```
func --version
4.0.4915
```

**Comment by saipuli** [comment] 2023-02-27 19:12
Experiencing this issue. Happy to provide any additional info for triage.

Computer: MacBook M1 Pro, running Ventura 13.2.1
```
func --version
4.0.5030
```

```
dotnet --list-sdks
7.0.200 [/usr/local/share/dotnet/sdk]
```

```
func new --name ProcessChange --template ServiceBusTopicTrigger
Select a number for template:Function name: ProcessChange
Restore failed.
Post action failed.

The function "ProcessChange" was created successfully from the "ServiceBusTopicTrigger" template.
```

**Comment by c0g1t8** [comment] 2023-03-23 23:38
I'm seeing the _Restore failed_ and _Post action failed_ when creating a new isoalated azure function.  I get the same error using _net6.0_ as well.

``` powershell
PS C:\git\bug-free-sniffle\apitest> func init --worker-runtime dotNetIsolated --target-framework net7.0 

Writing C:\git\bug-free-sniffle\apitest\.vscode\extensions.json
PS C:\git\bug-free-sniffle\apitest> func new --name WeatherForecastFunction -t HttpTrigger -a anonymous
Use the up/down arrow keys to select a template:Function name: WeatherForecastFunction
Restore failed.
Post action failed.

The function "WeatherForecastFunction" was created successfully from the "HttpTrigger" template.
PS C:\git\bug-free-sniffle\apitest> 
```
I have the following versions installed
``` powershell
PS C:\git\bug-free-sniffle> dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
6.0.407 [C:\Program Files\dotnet\sdk]
7.0.202 [C:\Program Files\dotnet\sdk]
7.0.300-preview.23122.5 [C:\Program Files\dotnet\sdk]
PS C:\git\bug-free-sniffle> func --version
4.0.4915
PS C:\git\bug-free-sniffle> node --version
v16.12.0
PS C:\git\bug-free-sniffle> 
```
I don't see these messages when creating a new in-process azure function.
```powershell
PS C:\git\bug-free-sniffle\apitest> func init --worker-runtime dotNet                                  

Writing C:\git\bug-free-sniffle\apitest\.vscode\extensions.json
PS C:\git\bug-free-sniffle\apitest> func new --name WeatherForecastFunction -t HttpTrigger -a anonymous
Use the up/down arrow keys to select a template:Function name: WeatherForecastFunction

The function "WeatherForecastFunction" was created successfully from the "HttpTrigger" template.
PS C:\git\bug-free-sniffle\apitest> 
```
Is there a timeline for resolving this?  The messages appear to be erroneous or superfluous since the function created is functional. But, it is annoying.

**Comment by c0g1t8** [comment] 2023-03-25 07:19
@fabiocav @soninaren 

I've just verifed the issue is in the [template](https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/HttpTrigger-CSharp-Isolated/.template.config/template.json).

```powershell
# install the template package from Nuget
dotnet new install Microsoft.Azure.Functions.Worker.ItemTemplates::4.0.2288
# create new isolated function
dotnet new http --name WeatherForecastFunction1 --namespace apitest --language "c#" --AccessRights anonymous
```

```powershell
PS C:\git\bug-free-sniffle\apitest> # install the template package from Nuget
PS C:\git\bug-free-sniffle\apitest> dotnet new install Microsoft.Azure.Functions.Worker.ItemTemplates::4.0.2288
The following template packages will be installed:
   Microsoft.Azure.Functions.Worker.ItemTemplates::4.0.2288

Success: Microsoft.Azure.Functions.Worker.ItemTemplates::4.0.2288 installed the following templates:
Template Name           Short Name       Language  Tags
----------------------  ---------------  --------  ----------------------------------------
BlobTrigger             blob             [C#],F#   Azure Function/Trigger/Blob
CosmosDBTrigger         cosmos,CosmosDB  [C#],F#   Azure Function/Trigger/Cosmos DB        
EventGridTrigger        eventgrid        [C#],F#   Azure Function/Trigger/EventGrid        
EventHubTrigger         eventhub         [C#],F#   Azure Function/Trigger/EventHub
HttpTrigger             http             [C#],F#   Azure Function/Trigger/Http
QueueTrigger            queue            [C#],F#   Azure Function/Trigger/Storage Queue    
RabbitMQTrigger         rqueue           [C#]      Azure Function/Trigger/RabbitMQ Queue   
ServiceBusQueueTrigger  squeue           [C#]      Azure Function/Trigger/Service Bus/Queue
ServiceBusTopicTrigger  stopic           [C#]      Azure Function/Trigger/Service Bus/Topic
SignalRTrigger          signalr          [C#]      Azure Function/Trigger/Http/SignalR     
TimerTrigger            timer            [C#],F#   Azure Function/Trigger/Timer

PS C:\git\bug-free-sniffle\apitest> # create new isolated function
PS C:\git\bug-free-sniffle\apitest> dotnet new http --name WeatherForecastFunction1 --namespace apitest --language "c#" --AccessRights anonymous
'.
info : Restoring packages for C:\git\bug-free-sniffle\apitest\apitest.csproj...
info : Package 'Microsoft.Azure.Functions.Worker.Extensions.Http' is compatible with all the specified frameworks in project 'C:\git\bug-free-sniffle\apitest\apitest.csproj'.info : PackageReference for package 'Microsoft.Azure.Functions.Worker.Extensions.Http' version '3.0.13' updated in file 'C:\git\bug-free-sniffle\apitest\apitest.csproj'.
info : Assets file has not changed. Skipping assets file writing. Path: C:\git\bug-free-sniffle\apitest\obj\project.assets.json
log  : Restored C:\git\bug-free-sniffle\apitest\apitest.csproj (in 309 ms).
Successfully added a reference to the project file.

Restoring C:\git\bug-free-sniffle\apitest\WeatherForecastFunction1.cs:
C:\git\bug-free-sniffle\apitest\WeatherForecastFunction1.cs(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. 
 Line 1, position 1.
Restore failed.
Post action failed.


An update for template package 'Microsoft.Azure.Functions.Worker.ItemTemplates::4.0.2288' is available.
To update the package use:
   dotnet new install Microsoft.Azure.Functions.Worker.ItemTemplates::4.0.2408
```

**Comment by surgupta-msft** [comment] 2024-11-13 23:00
Tried with the latest coretools version 4.0.6594 and net8.0 and did not see any issue. If still facing the issue, please create a new issue so we can take a fresh look with the latest versions.

**Closed by surgupta-msft** 2024-11-13 23:00 UTC
Labels: Needs: Triage (Functions)
