### ISSUE TITLE
Log filtering by category stopped working with release 3.0.2852

### ISSUE THREAD

**Issue by mj1856** [Azure/azure-functions-core-tools#2230] opened 2020-09-18 01:41 UTC
Log filtering by category, [as described in the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#log-configuration-in-hostjson), worked in release 3.0.2798 but is broken in the following release 3.0.2852

Given the following function app (.net core 3.1, functions v3, Windows):

```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public class Function1
    {
        private readonly ILogger _testLogger;

        public Function1(ILoggerFactory loggerFactory)
        {
            _testLogger = loggerFactory.CreateLogger("Test");
        }

        [FunctionName("Function1")]
        public IActionResult Run(
            [HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequest req,
            ILogger logger)
        {
            logger.LogInformation("Log information to the default logger");
            logger.LogWarning("Log a warning to the default logger");

            _testLogger.LogInformation("Log information to the Test logger");
            _testLogger.LogWarning("Log a warning to the Test logger");

            return new OkResult();
        }
    }
}

```

And `host.json`

```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "Test": "Warning"
    }
  }
}
```

Test with the working build first.

`npm install --global azure-functions-core-tools@3.0.2798` 
`func start --build`

```
Azure Functions Core Tools (3.0.2798 Commit hash: d9d99872a51c04b1c2783198b1ee1104da6b064f)
Function Runtime Version: 3.0.14191.0
...
```

Hit the HTTP endpoint and find the the console logs:
```
[9/18/2020 1:32:09 AM] Log information to the default logger
[9/18/2020 1:32:09 AM] Log a warning to the default logger
[9/18/2020 1:32:09 AM] Log a warning to the Test logger
```

As expected, the default logger got both information and warning messages, but the Test logger got only the warning - the filter worked.

Now try the same code with the failing version:

`npm install --global azure-functions-core-tools@3.0.2852` 
`func start --build`

```
Azure Functions Core Tools (3.0.2852 Commit hash: d1c2c8e7dc10a94a399246dda94049a7dbf0383d)
Function Runtime Version: 3.0.14287.0
...
```

Hit the HTTP endpoint and find the the console logs:
```
Log information to the default logger
Log a warning to the default logger
Log information to the Test logger
Log a warning to the Test logger
```

The log filter didn't work. All four messages are shown.  (Also there's no timestamps, but I can live with that.)

I also tried filtering them in DI startup with:

```csharp
builder.services.AddLogging(loggingBuilder =>
{
    loggingBuilder.AddFilter("Test", LogLevel.Warning);
});
```
... which also worked before and doesn't now.

In my real-world application, this is problematic because I use Entity Framework and dumps a ton of extra info to the logs including SQL queries, etc.  I had filtered them out with `"Microsoft.EntityFrameworkCore"` in the host.json, but after upgrading to the current tools, the filter stopped working.

**Comment by mj1856** [comment] 2020-09-18 01:55
And yes, the issue persists with the latest release 3.0.2912

**Comment by sonic1981** [comment] 2020-09-18 08:39
Might be related to this https://github.com/Azure/azure-functions-core-tools/issues/2216

**Comment by sonic1981** [comment] 2020-09-18 08:41
and this https://github.com/Azure/azure-functions-core-tools/issues/2220

**Comment by apawast** [comment] 2020-09-22 18:07
@pragnagopa can we close this as a duplicate of the issue cause by the verbosity change?

**Comment by pragnagopa** [comment] 2020-09-22 18:36
Thanks for reporting the issue. I will investigate if this issue is fixed in commit #d552c6741a37422684f0efab41d541ebad2b2bd2

**Comment by pragnagopa** [comment] 2020-09-22 19:12
Verified this issue is addressed. Next release will include the fix. Until we update the tooling, please use artifacts for the release: https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2931

**Closed by pragnagopa** 2020-09-22 19:13 UTC

**Comment by mj1856** [comment] 2020-09-23 16:23
It works.  Thanks!

**Comment by mj1856** [comment] 2020-09-23 16:35
@pragnagopa - small nitpick:  Thanks for adding the timestamps back and making them ISO 8601!  However, they are coming out as `[2020-09-23T16:22:41.337]` and instead should be `[2020-09-23T16:22:41.337Z]`.  The trailing `Z` is important, as the ISO8601 spec says that if no `Z` (or offset) is present, then the value should be interpreted as *local time*.  Since you're logging UTC time, please add the `Z`.  

You can use the `K` specifier with `DateTime.UtcNow` [on line 94](https://github.com/Azure/azure-functions-core-tools/blob/3a59efba0cbf74dfaf1911de5f073df97259d9f3/src/Azure.Functions.Cli/Diagnostics/ColoredConsoleLogger.cs#L94).  You might also want to pass `CultureInfo.InvariantCulture` to prevent strange output when the current culture uses a non-Gregorian calendar.
