### ISSUE TITLE
func azure functionapp fetch-app-settings <functionappname> not working

### ISSUE THREAD

**Issue by bryceba** [Azure/azure-functions-core-tools#691] opened 2018-09-04 09:40 UTC
Since I updated to 2.0.1-beta.37 **func azure functionapp fetch-app-settings <functionappname>** returns **Can't find app with name <functionappname>** 

It does take some time to return this result

**Comment by ahmelsayed** [comment] 2018-09-04 17:30
are you logged in the correct account with `az`? Versions `>= beta.37` share the same login context with `az`, if you do `az functionapp list --query "[].name"`, do you see your app in the list?

**Comment by bryceba** [comment] 2018-09-05 05:46
Yes, I am logged in with az - I ran the functionapp list statement and can see my functionapp name in the list. Still no luck

**Comment by ahmelsayed** [comment] 2018-09-20 23:39
I think the root cause might be #738. I'm closing this one in favor of the other issue since it has more information.,

**Closed by ahmelsayed** 2018-09-20 23:39 UTC
Labels: investigate
