### ISSUE TITLE
Debugging Azure Function Error (System.Private.CoreLib: The given key 'LogType' was not present in the dictionary)

### ISSUE THREAD

**Issue by clizana** [Azure/azure-functions-core-tools#1805] opened 2020-02-05 15:05 UTC
Hello,
I'm working with Python 3.6.9 and ADLSv2, using blob triggers.
When I switch to a blobstorage account instead of ADLSv2 works perfect so the problem is definitely related to ADLSv2.

Here is the log of my test:

> Azure Functions Core Tools (2.7.1948 Commit hash: 29a0626ded3ae99c4111f66763f27bb9fb564103)
Function Runtime Version: 2.0.12888.0
[2/5/20 2:51:47 PM] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '4a7d7027-3037-4031-a543-901a2de9a936'
[2/5/20 2:51:47 PM] Reading host configuration file '/home/clizana/excel/host.json'
[2/5/20 2:51:47 PM] Host configuration file read:
[2/5/20 2:51:47 PM] {
[2/5/20 2:51:47 PM]   "version": "2.0",
[2/5/20 2:51:47 PM]   "extensionBundle": {
[2/5/20 2:51:47 PM]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2/5/20 2:51:47 PM]     "version": "[1.*, 2.0.0)"
[2/5/20 2:51:47 PM]   }
[2/5/20 2:51:47 PM] }
[2/5/20 2:51:47 PM] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /tmp/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2/5/20 2:51:47 PM] Found a matching extension bundle at /tmp/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1
[2/5/20 2:51:47 PM] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2/5/20 2:51:47 PM] Skipping bundle download since it already exists at path /tmp/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1
[2/5/20 2:51:47 PM] Loading Extention bundle from /tmp/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1
[2/5/20 2:51:47 PM] Reading functions metadata
[2/5/20 2:51:48 PM] 1 functions found
[2/5/20 2:51:48 PM] Loading startup extension 'AzureStorage'
[2/5/20 2:51:48 PM] Loaded extension 'AzureStorage' (3.0.10.0)
[2/5/20 2:51:48 PM] Initializing Warmup Extension.
[2/5/20 2:51:48 PM] Initializing Host. OperationId: '4a7d7027-3037-4031-a543-901a2de9a936'.
[2/5/20 2:51:48 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=4a7d7027-3037-4031-a543-901a2de9a936
[2/5/20 2:51:48 PM] LoggerFilterOptions
[2/5/20 2:51:48 PM] {
[2/5/20 2:51:48 PM]   "MinLevel": "None",
[2/5/20 2:51:48 PM]   "Rules": [
[2/5/20 2:51:48 PM]     {
[2/5/20 2:51:48 PM]       "ProviderName": null,
[2/5/20 2:51:48 PM]       "CategoryName": null,
[2/5/20 2:51:48 PM]       "LogLevel": null,
[2/5/20 2:51:48 PM]       "Filter": "<AddFilter>b__0"
[2/5/20 2:51:48 PM]     },
[2/5/20 2:51:48 PM]     {
[2/5/20 2:51:48 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2/5/20 2:51:48 PM]       "CategoryName": null,
[2/5/20 2:51:48 PM]       "LogLevel": "None",
[2/5/20 2:51:48 PM]       "Filter": null
[2/5/20 2:51:48 PM]     },
[2/5/20 2:51:48 PM]     {
[2/5/20 2:51:48 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2/5/20 2:51:48 PM]       "CategoryName": null,
[2/5/20 2:51:48 PM]       "LogLevel": null,
[2/5/20 2:51:48 PM]       "Filter": "<AddFilter>b__0"
[2/5/20 2:51:48 PM]     }
[2/5/20 2:51:48 PM]   ]
[2/5/20 2:51:48 PM] }
[2/5/20 2:51:48 PM] FunctionResultAggregatorOptions
[2/5/20 2:51:48 PM] {
[2/5/20 2:51:48 PM]   "BatchSize": 1000,
[2/5/20 2:51:48 PM]   "FlushTimeout": "00:00:30",
[2/5/20 2:51:48 PM]   "IsEnabled": true
[2/5/20 2:51:48 PM] }
[2/5/20 2:51:48 PM] SingletonOptions
[2/5/20 2:51:48 PM] {
[2/5/20 2:51:48 PM]   "LockPeriod": "00:00:15",
[2/5/20 2:51:48 PM]   "ListenerLockPeriod": "00:00:15",
[2/5/20 2:51:48 PM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2/5/20 2:51:48 PM]   "LockAcquisitionPollingInterval": "00:00:05",
[2/5/20 2:51:48 PM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2/5/20 2:51:48 PM] }
[2/5/20 2:51:48 PM] QueuesOptions
[2/5/20 2:51:48 PM] {
[2/5/20 2:51:48 PM]   "BatchSize": 16,
[2/5/20 2:51:48 PM]   "NewBatchThreshold": 8,
[2/5/20 2:51:48 PM]   "MaxPollingInterval": "00:00:02",
[2/5/20 2:51:48 PM]   "MaxDequeueCount": 5,
[2/5/20 2:51:48 PM]   "VisibilityTimeout": "00:00:00"
[2/5/20 2:51:48 PM] }
[2/5/20 2:51:48 PM] BlobsOptions
[2/5/20 2:51:48 PM] {
[2/5/20 2:51:48 PM]   "CentralizedPoisonQueue": false
[2/5/20 2:51:48 PM] }
[2/5/20 2:51:48 PM] HttpOptions
[2/5/20 2:51:48 PM] {
[2/5/20 2:51:48 PM]   "DynamicThrottlesEnabled": false,
[2/5/20 2:51:48 PM]   "MaxConcurrentRequests": -1,
[2/5/20 2:51:48 PM]   "MaxOutstandingRequests": -1,
[2/5/20 2:51:48 PM]   "RoutePrefix": "api"
[2/5/20 2:51:48 PM] }
[2/5/20 2:51:48 PM] Starting JobHost
[2/5/20 2:51:48 PM] Starting Host (HostId=vmlinux-2022498198, InstanceId=0f069629-ec8e-4c9e-a8cd-ee3895aa3db4, Version=2.0.12888.0, ProcessId=17832, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2/5/20 2:51:49 PM] Loading functions metadata
[2/5/20 2:51:49 PM] 1 functions loaded
[2/5/20 2:51:49 PM] Starting worker process:python3  "/usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/python/3.6/LINUX/X64/worker.py" --host 127.0.0.1 --port 36985 --workerId dd828dc3-2a5b-4ae6-904c-26b7dab67fbe --requestId 2a64e5de-9d7c-472e-a81a-da4ee7c04a1f --grpcMaxMessageLength 134217728
[2/5/20 2:51:49 PM] python3 process with Id=17870 started
[2/5/20 2:51:49 PM] Generating 1 job function(s)
[2/5/20 2:51:49 PM] Found the following functions:
[2/5/20 2:51:49 PM] Host.Functions.toCSV
[2/5/20 2:51:49 PM]
[2/5/20 2:51:49 PM]  INFO: Starting Azure Functions Python Worker.
[2/5/20 2:51:49 PM]  INFO: Worker ID: dd828dc3-2a5b-4ae6-904c-26b7dab67fbe, Request ID: 2a64e5de-9d7c-472e-a81a-da4ee7c04a1f, Host Address: 127.0.0.1:36985
[2/5/20 2:51:49 PM]  INFO: Successfully opened gRPC channel to 127.0.0.1:36985
[2/5/20 2:51:51 PM] Initializing function HTTP routes
[2/5/20 2:51:51 PM] No HTTP routes mapped
[2/5/20 2:51:51 PM]
[2/5/20 2:51:51 PM] Host initialized (2048ms)
[2/5/20 2:51:51 PM]  INFO: Received WorkerInitRequest, request ID 2a64e5de-9d7c-472e-a81a-da4ee7c04a1f
[2/5/20 2:51:51 PM] Host started (2318ms)
[2/5/20 2:51:51 PM] Job host started
Hosting environment: Production
Content root path: /home/clizana/excel
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[2/5/20 2:51:51 PM]  INFO: Received FunctionLoadRequest, request ID: 2a64e5de-9d7c-472e-a81a-da4ee7c04a1f, function ID: 63061ab7-af12-4931-8a03-0ef26c415545
[2/5/20 2:51:52 PM] An unhandled exception has occurred. Host is shutting down.
[2/5/20 2:51:52 PM] System.Private.CoreLib: The given key 'LogType' was not present in the dictionary.
[2/5/20 2:51:52 PM] Stopping host...
[2/5/20 2:51:52 PM] Stopping JobHost
[2/5/20 2:51:52 PM] Job host stopped
[2/5/20 2:51:52 PM] Host shutdown completed.
Application is shutting down...

> 

I saw the same issue here **https://github.com/Azure/azure-webjobs-sdk/issues/2395** but I don't know if will be fixed in the core tools too.

**Comment by ankitkumarr** [comment] 2020-02-12 05:44
@clizana, the core-tools transiently uses webjobs-sdk through the functions host. This is likely a host or webjobs-sdk issue. If the issue is indeed the one you tagged (which seems to be the case), as soon as that's fixed and released, the next core-tools release would have the fix too.

I am closing this as dup of https://github.com/Azure/azure-webjobs-sdk/issues/2395

Please let us know if you have further questions.

**Closed by ankitkumarr** 2020-02-12 05:44 UTC
Labels: Needs: Triage :mag:
