### ISSUE TITLE
Create a 64-bit build of func.exe

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-core-tools#117] opened 2017-04-14 22:17 UTC
Would be func64.exe

Edit: there is a 64 build in the latest release https://github.com/Azure/azure-functions-cli/releases/

**Comment by kr4ster** [comment] 2017-07-13 12:51
If all else fails, you can pull down the project, open the properties for the cli project, uncheck the box for "Prefer 32-bit" under the "Build" tab and rebuild the project.  Once I did this, I made a backup of the existing install `%LOCALAPPDATA%\Azure.Functions.Cli\1.0.0-beta.100` and overwrote the existing files with  the newly compiled files.

**Comment by aarondcoleman** [comment] 2017-07-18 20:37
👍 for a 64-bit build

**Comment by MikeWilliams-UK** [comment] 2017-08-16 06:30
I just downloaded the source and I get 55 errors when I try to compile it...
Am I doing something wrong (I am using VS2015)?

**Comment by ahmelsayed** [comment] 2017-08-16 15:57
@MikeWilliams-UK what errors are you getting? AppVayor doesn't run automatically and since I'm the only one committing to this repo, I never bothered update it. 

Can you try excluding the test project? I'm using a private xunit from the xunit myget feed to get around an annoying [bug ](https://github.com/Microsoft/vstest/issues/811#issuecomment-314242326) on my machine. I should add that to the .nuget config.

**Comment by ahmelsayed** [comment] 2017-08-16 16:44
I created a signed x64 build and added it to the release notes for 1.0.1 https://github.com/Azure/azure-functions-cli/releases/tag/1.0.1, so give that a try. 
I'll take a look at the build errors in appVayor

**Comment by MikeWilliams-UK** [comment] 2017-08-16 16:55
Thanks I will give it a try tomorrow and let you know if it works (for me)

**Comment by MikeWilliams-UK** [comment] 2017-08-17 11:36
I have just tested the x64 build and I can confirm that it works a treat.

Thanks for your valuable time.

**Comment by wesselkranenborg** [comment] 2017-11-02 09:35
Is there a later x64 CLI release available? For the 1.0.6 release for example?

**Comment by miguelmartin75** [comment] 2018-01-19 23:11
How do we use this in Visual Studio to build the project? I don't understand. I have a dependency that is 64 bit and is not compatible with the 32 bit build that VS is producing. In 64-bit mode the .dll for my Azure functions are not being produced (C#).

**Comment by EricJizbaMSFT** [comment] 2018-02-05 16:32
Can we get an easier way to install the 64-bit build? Or at least documentation on the best way to install? Like @miguelmartin75 mentioned, copying files to a location on disk is not ideal.

Fwiw, the 64-bit build is useful with the VS Code [extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions) for Azure Functions, since the C# Debugger for VS Code [only supports](https://github.com/OmniSharp/omnisharp-vscode/issues/1716) attaching to 64-bit processes.

**Comment by nickmkk** [comment] 2018-06-21 15:42
It seems my build is using cli v1.2.0 but there isn't a release for that version?

![image](https://user-images.githubusercontent.com/10885165/41729767-b444f702-753f-11e8-8a12-af7932e1fa71.png)

**Comment by Frankwayne** [comment] 2018-09-18 20:14
If you want to debug in visual studio with the 64 bit version of the azure functions CLI you will need to do the following.   I was working with the V1  release branch so  be sure to grab the right CLI for the azure functions you wish to run   

Its kinda   crazy and every time your azure function and web job tools  extension updates you will need to run this fix

Pretty much you have to go to where your Azure function CLI is install for this extenion.    Default location is here.  I imagine once the extension automatically updates  the version will change.  E.G.  1.3.0
 
C:\Users\A750501\AppData\Local\AzureFunctionsTools\Releases\1.3.0\cli    
 
Delete all of those fies inside of the cli  folder.     Download the   Azure.Functions.Cli.x64.zip   of the latest v1   releases  
 
put the content of the zip folder in the cli  folder.   Boom  you are now running the 64 bit  Azure functions

**Comment by Frankwayne** [comment] 2018-09-19 01:59
@paulbatum   that is a much better approach and I would also recommend other people follow your approach.  I had no idea you could do such a task and it is awesome to learn how to switch profiles on demand instead of fooling the extension

**Comment by ryancole** [comment] 2018-10-29 17:31
@paulbatum or anybody who may know,

Is the 2.x version line of the CLI tools strictly for the v2 of the Functions service itself? We're using 1.x for the .NET Framework support, but are needing an x64 CLI. I'm unclear whether the versioning for this CLI tool set is the same as saying "v1 or v2 of Functions service".

Will the latest 2.x builds of this CLI tool work for the 1.x version line of Functions too?

**Comment by ahmelsayed** [comment] 2018-10-30 18:07
Yes, your edit is correct. the version VS uses is different from the version of the core-tools. It's confusing I know, but they have a different release process than the core-tools.

**Comment by sdg002** [comment] 2019-04-01 18:01
Sorry, I am confused, please help. I am looking for the 64 bit version of func.exe so that I can debug a Version 1 Azure function using Visual Studio 2017. Which version of the tool should I use?   Thank you.

**Comment by soninaren** [comment] 2019-04-16 00:21
Closing this one since we do create 64 bit exe for CLI.

**Closed by soninaren** 2019-04-16 00:21 UTC
Labels: feature

**Comment by paulbatum** [comment] 2019-04-16 22:10
And for completeness, tracking of x64 development in Visual Studio is here:
https://github.com/Azure/Azure-Functions/issues/376
