### ISSUE TITLE
SSL problems affecting much of func's functionality

### ISSUE THREAD

**Issue by NANASHI0X74** [Azure/azure-functions-core-tools#2017] opened 2020-06-03 10:09 UTC
I have func installed on ubuntu 20.04 via:
```
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install azure-functions-core-tools
```

but a lot of commands fail because of SSL related errors:
- `func new` errors with:
```
The SSL connection could not be established, see inner exception.
```
(This is the only output and I don't know how to access the 'inner exception')
- I was able to run `func init` in a typescript project, but when I try to run `func start` it fails with following output:
```
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.2184 Commit hash: 5afacc827c2848e4debc23bb96604f1ffce09cc7)
Function Runtime Version: 2.0.12961.0
[03/06/2020 09:59:00] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[03/06/2020 09:59:00] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[03/06/2020 09:59:00] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[03/06/2020 09:59:01] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'bc391a03-3d53-423a-b8d1-6fe0e14d278a'
[03/06/2020 09:59:01] Reading host configuration file 'censored'
[03/06/2020 09:59:01] Host configuration file read:
[03/06/2020 09:59:01] {
[03/06/2020 09:59:01]   "version": "2.0",
[03/06/2020 09:59:01]   "extensionBundle": {
[03/06/2020 09:59:01]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[03/06/2020 09:59:01]     "version": "[1.*, 2.0.0)"
[03/06/2020 09:59:01]   }
[03/06/2020 09:59:01] }
[03/06/2020 09:59:01] Reading functions metadata
[03/06/2020 09:59:01] 0 functions found
[03/06/2020 09:59:01] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /tmp/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[03/06/2020 09:59:01] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[03/06/2020 09:59:01] A host error has occurred during startup operation 'bc391a03-3d53-423a-b8d1-6fe0e14d278a'.
[03/06/2020 09:59:01] System.Net.Http: The SSL connection could not be established, see inner exception. System.Private.CoreLib: The remote certificate is invalid according to the validation procedure.
Value cannot be null.
Parameter name: provider
Application is shutting down...
[03/06/2020 09:59:01] Initialization cancellation requested by runtime.
Hosting environment: Production
Content root path: censored
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[03/06/2020 09:59:01] Stopping host...
[03/06/2020 09:59:01] Host shutdown completed.
```

**Comment by GideonWislang** [comment] 2020-06-06 05:02
Same issue, did you manage to resolve it?

**Comment by anthonychu** [comment] 2020-06-06 05:35
@GideonWislang From the error in #2024, it looks like the SSL error is caused by the cert from the Cosmos DB emulator in Parallels not being trusted by func on macOS, which might be different from this issue (looks like a cert error from the CDN while downloading extension bundles). We can troubleshoot in the other thread.

@NANASHI0X74 Are you still experiencing this error? Can you try to access the URL in the output in a browser? https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json

**Comment by NANASHI0X74** [comment] 2020-06-06 13:14
I can access that URL. I've never been able to get func running properly like I intended actually, had the same error a few weeks ago, but eventually gave up fixing it and did what I wanted manually. Now I wanted to test a function's logic locally, but worked around the problem by starting a local express server

**Comment by anthonychu** [comment] 2020-06-09 21:10
@NANASHI0X74 Are you still seeing this error? We've validated that the SSL cert is correct. Are you behind a proxy?

**Comment by janpro0706** [comment] 2020-06-12 08:19
similar issue on Ubuntu 18.04, azure-function-core-tools@3.
I initiated with Azure functions extensions in VSCode. then, ran in locally with [F5]. But, got error log:

```bash
Azure Functions Core Tools (3.0.2534 Commit hash: bc1e9efa8fa78dd1a138dd1ac1ebef97aac8d78e)
Function Runtime Version: 3.0.13353.0
[2020. 6. 12. 오전 7:39:07] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2020. 6. 12. 오전 7:39:07] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2020. 6. 12. 오전 7:39:07] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2020. 6. 12. 오전 7:39:07] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'bb600e21-4945-402c-b2cb-73f920f17a0f'
[2020. 6. 12. 오전 7:39:08] Reading host configuration file 'censored'
[2020. 6. 12. 오전 7:39:08] Host configuration file read:
[2020. 6. 12. 오전 7:39:08] {
[2020. 6. 12. 오전 7:39:08]   "version": "2.0",
[2020. 6. 12. 오전 7:39:08]   "extensionBundle": {
[2020. 6. 12. 오전 7:39:08]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2020. 6. 12. 오전 7:39:08]     "version": "[1.*, 2.0.0)"
[2020. 6. 12. 오전 7:39:08]   }
[2020. 6. 12. 오전 7:39:08] }
[2020. 6. 12. 오전 7:39:08] Reading functions metadata
[2020. 6. 12. 오전 7:39:08] 3 functions found
[2020. 6. 12. 오전 7:39:08] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /tmp/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2020. 6. 12. 오전 7:39:08] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2020. 6. 12. 오전 7:39:08] Downloading extension bundle from https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.1.1/Microsoft.Azure.Functions.ExtensionBundle.1.1.1.zip to /tmp/7b6a5aeb-6802-440e-bec0-9a836ed0a2e6/Microsoft.Azure.Functions.ExtensionBundle.1.1.1.zip
Hosting environment: Production
Content root path: censored
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 252
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
Application is shutting down...
[2020. 6. 12. 오전 7:41:22] Stopping host...
[2020. 6. 12. 오전 7:41:22] Host shutdown completed.
```
I also found that it works fine sometimes. It worked fine when 'ExtensionBundles' is downloaded and copied to '/tmp/Functions' correctly, otherwise, got error. I wonder that this issue also related to SSL error.

**Comment by Bugzey** [comment] 2021-05-11 10:13
Getting the exact same error on Ubuntu 20.04 via WSL2.

```
$ func start --verbose
Found Python version 3.8.5 (python3).

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

[2021-05-11T10:04:50.798Z] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'fce97a95-360e-4931-a3cf-d52814b9916b'
[2021-05-11T10:04:50.834Z] Reading host configuration file '/mnt/c/Users/rdimitrov/Desktop/BD Box API Client/box_api_client/host.json'
[2021-05-11T10:04:50.836Z] Host configuration file read:
[2021-05-11T10:04:50.836Z] {
[2021-05-11T10:04:50.836Z]   "version": "2.0",
[2021-05-11T10:04:50.837Z]   "logging": {
[2021-05-11T10:04:50.837Z]     "applicationInsights": {
[2021-05-11T10:04:50.837Z]       "samplingSettings": {
[2021-05-11T10:04:50.838Z]         "isEnabled": true,
[2021-05-11T10:04:50.838Z]         "excludedTypes": "Request"
[2021-05-11T10:04:50.838Z]       }
[2021-05-11T10:04:50.838Z]     }
[2021-05-11T10:04:50.838Z]   },
[2021-05-11T10:04:50.839Z]   "extensionBundle": {
[2021-05-11T10:04:50.839Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-05-11T10:04:50.839Z]     "version": "[1.*, 2.0.0)"
[2021-05-11T10:04:50.839Z]   }
[2021-05-11T10:04:50.839Z] }
[2021-05-11T10:04:50.861Z] Loading functions metadata
[2021-05-11T10:04:50.875Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:node
[2021-05-11T10:04:50.880Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:java
[2021-05-11T10:04:50.883Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:powershell
[2021-05-11T10:04:50.891Z] Reading functions metadata
[2021-05-11T10:04:50.917Z] 1 functions found
[2021-05-11T10:04:50.926Z] 1 functions loaded
[2021-05-11T10:04:50.931Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /home/rdimitrov/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2021-05-11T10:04:50.932Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2021-05-11T10:04:51.049Z] A host error has occurred during startup operation 'fce97a95-360e-4931-a3cf-d52814b9916b'.
[2021-05-11T10:04:51.049Z] System.Net.Http: The SSL connection could not be established, see inner exception. System.Private.CoreLib: The remote certificate is invalid according to the validation procedure.
Value cannot be null. (Parameter 'provider')
[2021-05-11T10:04:51.111Z] Initialization cancellation requested by runtime.
[2021-05-11T10:04:51.117Z] Stopping host...
[2021-05-11T10:04:51.118Z] Host shutdown completed.
```

I can open the link mentioned in the logs just fine with `curl`.

`func` did function properly a few months ago. I recently updated OpenSSL with a version that's not in the official repos, which might be related to this issue even though is picked up fine by the rest of the system:
```
$ openssl version -a
OpenSSL 1.1.1k  25 Mar 2021
built on: Thu Apr 29 14:35:33 2021 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
Seeding source: os-specific
```

General system info:
```
$ uname -a
Linux RADOSLAV-NB 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fabiocav** [comment] 2021-05-25 20:33
@janpro0706 the exception is similar, but the underlying issue you're seeing seems to have a different root cause. Can you please open a separate issue with the details of what you're seeing? Thanks!

**Comment by ShuPink** [comment] 2021-06-10 05:45
I don't know if this will help anyone else but I was also running into this problem when trying to run a function locally, and removing the extensionBundle from the host.json got things working for me: 

```
[2021-06-10T05:15:49.423Z] A host error has occurred during startup operation '62f38e1e-etc...'.
[2021-06-10T05:15:49.423Z] System.Net.Http: The SSL connection could not be established, see inner exception. System.Private.CoreLib: The remote certificate is invalid according to the validation procedure.
Value cannot be null. (Parameter 'provider')
```

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },

  "extensionBundle": {  // remove this entry
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```
I only tried this because I stumbled across this stackoverflow answer here: 
https://stackoverflow.com/a/65418092

**Comment by LHousehold** [comment] 2021-06-16 17:18
But if the extension bundle is removed, then there's no way for func tools to access cosmos db emulator using bindings.

**Comment by apawast** [comment] 2021-11-09 15:53
@NANASHI0X74 are you still experiencing this issue?

**Comment by NANASHI0X74** [comment] 2021-11-11 10:23
I don't work at the same place anymore (running a different system configuration now) and haven't used the tool in some time, so can't really give any feedback beyond that I never got it running

**Comment by apawast** [comment] 2021-11-23 18:54
@NANASHI0X74 since you are no longer working with this, I will be closing this issue. If anyone else is still experiencing this issue please feel free to open another one.

**Closed by apawast** 2021-11-23 18:54 UTC
Labels: Needs: Attention :wave:
