### ISSUE TITLE
FUNCTIONS_WORKER_RUNTIME not set correctly when publishing with dotnet-isolated and --force

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2615] opened 2021-06-05 22:55 UTC
`dotnet-isolated` is incorrectly set to `dotnetIsolated`:

https://github.com/Azure/azure-functions-core-tools/blob/1bd13b4e0d5678e51da1aad3e202df0852cf2ce7/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L218

Also:

https://github.com/Azure/azure-functions-core-tools/blob/1bd13b4e0d5678e51da1aad3e202df0852cf2ce7/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L237

@brettsam @fabiocav @ankitkumarr

**Comment by forki** [comment] 2021-06-06 06:44
https://github.com/Azure/azure-functions-core-tools/blob/1bd13b4e0d5678e51da1aad3e202df0852cf2ce7/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L226 here it's used explicitly. Looks like ToString needs to be fixed and all those places changed to ToString

**Comment by forki** [comment] 2021-06-07 07:43
Ok so I can confirm that this is the issue. A potential fix is: https://github.com/Azure/azure-functions-core-tools/pull/2616

Also I found a workaround:

    func azure functionapp publish [FUNCTIONAPPNAME] --force
    func azure functionapp publish [FUNCTIONAPPNAME] -o -y


this just overwrites the broken settings after the publish

**Comment by fabiocav** [comment] 2021-06-24 20:41
Resolved by #2616

**Closed by fabiocav** 2021-06-24 20:41 UTC
Labels: bug
