### ISSUE TITLE
Output bindings not registered

### ISSUE THREAD

**Issue by JamieMagee** [Azure/azure-functions-core-tools#1257] opened 2019-04-29 08:21 UTC
I'm unable to get any output bindings to work when debugging locally using Azure Functions core tools. That includes using the example functions. (Duplicate of Azure/azure-functions-host#4335 as I'm not sure where the issue is exactly)

#### Repro steps

Debug the function attached at the bottom of the bug report. `context.bindings` only contains 1 binding, but it should include 2: An input and an output. Both bindings are correctly defined in `context.bindingDefinitions`.

Trigger using `curl localhost:7071/api/HttpTrigger`

##### Environment
- Arch Linux
- Azure Functions core tools: 2.5.553

<details>
<summary>Source</summary>

```json
{
  "bindings": [
    {
      "name": "req",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

```ts
import { AzureFunction, Context } from '@azure/functions';

const index: AzureFunction = async function (context: Context): Promise<void> {
    
};

export default index;
```
</details>

**Comment by ahmedelnably** [comment] 2019-04-30 18:13
Duplicate of https://github.com/Azure/azure-functions-host/issues/4335

**Closed by ahmedelnably** 2019-04-30 18:13 UTC
Labels: Needs: Triage :mag:
