### ISSUE TITLE
func new is not working for java

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-core-tools#2562] opened 2021-04-19 22:07 UTC
Probably, Java looks not supported for CoreTools, however, the experience looks misleading. 

```bash
a$ func init
Select a number for worker runtime:
1. dotnet
2. dotnet (isolated process)
3. node
4. python
5. java
6. powershell
7. custom
Choose option: 5
java
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing /home/ushio/Code/Project/Lima/CoreTools/java/.vscode/extensions.json
$ func new
Select a number for language:Select a number for template:Worker runtime 'java' is not a valid worker for a template.
```

If it is not available, we can cross out the 5. java.   For java, we usually, `maven` plugin. 

`func init` equivalent.

```bash
$ mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DjavaVersion=8
```

`func new` equivalent.

```bash
$ mvn azure-functions:add
[INFO] Step 2 of 4: Select function template
Choose from below options as template for new function 
0. HttpTrigger
1. BlobTrigger
2. QueueTrigger
3. TimerTrigger
4. EventGridTrigger
5. EventHubTrigger
6. CosmosDBTrigger
7. ServiceBusQueueTrigger
8. ServiceBusTopicTrigger
```

It also doesn't include `Kafka Trigger` it is on going, however, I don't know the ETA of RabbitMQ.  RabbitMQ has separate repo.
FYI: https://github.com/microsoft/azure-maven-plugins/issues/1423

@pragnagopa

**Comment by pragnagopa** [comment] 2021-04-19 22:43
This is issue is by design right now. azure-maven-plugin is the only support for command line development.

@TsuyoshiUshio - do you think we should show a error message or a warning to let users know to use maven plugin?

**Comment by TsuyoshiUshio** [comment] 2021-04-19 22:59
I think, just remove java from `func init` might be good to avoid confusion. What do you think?

**Comment by amamounelsayed** [comment] 2021-04-19 23:16
Thank you @TsuyoshiUshio this is duplicate to https://github.com/Azure/azure-functions-core-tools/issues/2542

**Comment by pragnagopa** [comment] 2021-04-20 00:23
closing this as dup

**Closed by pragnagopa** 2021-04-20 00:23 UTC
