### ISSUE TITLE
Can't determine Project to build. Expected 1 .csproj or .fsproj but found 3 when running "func start"

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-functions-core-tools#3594] opened 2024-02-14 15:06 UTC
The `func start` command used to work flawlessly but it started showing the subject error message. Further info:

- .NET SDK 8.0.101
- `func --version` reveals version 4.0.5455
- There is only one .csproj file in the function app's folder, but the function app is a part of a C# solution
- I launched VS Code to create and initialize a new minimal azure function app. The `func start` works.

**Comment by xandrw** [comment] 2024-02-15 15:01
I'm having the exact same issue.

**Comment by ryanzwe** [comment] 2024-02-16 02:30
Delete the /bin & obj folder

**Comment by Arash-Sabet** [comment] 2024-02-16 12:39
@ryanzwe It worked as a workaround but one has to keep doing it every single time. I think the root cause must be addressed.

**Comment by Arash-Sabet** [comment] 2024-02-16 12:56
@ryanzwe VS 2022 works smoothly but it becomes more annoying when one has to work by VS Code on macOS.

**Comment by xandrw** [comment] 2024-02-16 12:59
Delete `/bin` and `/obj` folders, downgrade packages until it works.

**Comment by Arash-Sabet** [comment] 2024-02-16 13:05
@xandrw which packages specifically?

**Comment by Hipster74** [comment] 2024-02-21 10:32
Adding to this issue.

- dotnet-isolated V4 durable function
- .NET SDK 8.0.201
- func --version version 4.0.5530
- There is only one .csproj file in the function app's folder, but the function app is a part of a C# solution

Func start gives error 'Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2'

If I delete /bin & /obj folder it builds, but fails to start function with:

`Could not load file or assembly 'Microsoft.Azure.WebJobs.Script.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3c5b9424214e8f8c'. The system cannot find the file specified.`

.csproj 

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.8.3" />
    <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.2" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.2.0" />
    <PackageReference Include="Result.Net" Version="1.5.0" />
  </ItemGroup>
  <ItemGroup>`

**Comment by dawidcieszynski** [comment] 2024-02-21 11:53
I got this issue when upgraded from Microsoft.Azure.Functions.Worker.Sdk 1.16.4 to 1.17.0
In my case temporary solution was to remove obj\Debug\net8.0\WorkerExtensions\WorkerExtensions.csproj before every function start.

(I upgraded because I had another issue with missing operation_Name in the application insights and now checking whether I need 1.17.0 or not :) )

**Comment by Hipster74** [comment] 2024-02-21 11:54
> > Adding to this issue.
> > 
> > * dotnet-isolated V4 durable function
> > * .NET SDK 8.0.201
> > * func --version version 4.0.5530
> > * There is only one .csproj file in the function app's folder, but the function app is a part of a C# solution
> > 
> > Func start gives error 'Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2'
> > If I delete /bin & /obj folder it builds, but fails to start function with:
> > `Could not load file or assembly 'Microsoft.Azure.WebJobs.Script.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3c5b9424214e8f8c'. The system cannot find the file specified.`
> > .csproj
> > `<Project Sdk="Microsoft.NET.Sdk"> <PropertyGroup> <TargetFramework>net8.0</TargetFramework> <AzureFunctionsVersion>v4</AzureFunctionsVersion> <RuntimeIdentifier>win-x64</RuntimeIdentifier> <PublishReadyToRun>true</PublishReadyToRun> <OutputType>Exe</OutputType> <ImplicitUsings>enable</ImplicitUsings> <Nullable>enable</Nullable> </PropertyGroup> <ItemGroup> <PackageReference Include="Azure.Data.Tables" Version="12.8.3" /> <PackageReference Include="Azure.Identity" Version="1.10.4" /> <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.1" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" /> <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" /> <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.2" /> <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.2.0" /> <PackageReference Include="Result.Net" Version="1.5.0" /> </ItemGroup> <ItemGroup>`
> 
> Try restore manually, or install that package individually, had this happen before on a dependent package needing newtonsoft, installing newtonsoft directly fixed it.

Thanks @ryanzwe , this issue is already handled here : [https://github.com/Azure/azure-functions-core-tools/issues/3602](url)

**Comment by ryanzwe** [comment] 2024-02-21 11:57
> > > Adding to this issue.
> > > 
> > > * dotnet-isolated V4 durable function
> > > * .NET SDK 8.0.201
> > > * func --version version 4.0.5530
> > > * There is only one .csproj file in the function app's folder, but the function app is a part of a C# solution
> > > 
> > > Func start gives error 'Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2'
> > > If I delete /bin & /obj folder it builds, but fails to start function with:
> > > `Could not load file or assembly 'Microsoft.Azure.WebJobs.Script.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3c5b9424214e8f8c'. The system cannot find the file specified.`
> > > .csproj
> > > `<Project Sdk="Microsoft.NET.Sdk"> <PropertyGroup> <TargetFramework>net8.0</TargetFramework> <AzureFunctionsVersion>v4</AzureFunctionsVersion> <RuntimeIdentifier>win-x64</RuntimeIdentifier> <PublishReadyToRun>true</PublishReadyToRun> <OutputType>Exe</OutputType> <ImplicitUsings>enable</ImplicitUsings> <Nullable>enable</Nullable> </PropertyGroup> <ItemGroup> <PackageReference Include="Azure.Data.Tables" Version="12.8.3" /> <PackageReference Include="Azure.Identity" Version="1.10.4" /> <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.1" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" /> <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" /> <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" /> <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.2" /> <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.2.0" /> <PackageReference Include="Result.Net" Version="1.5.0" /> </ItemGroup> <ItemGroup>`
> > 
> > 
> > Try restore manually, or install that package individually, had this happen before on a dependent package needing newtonsoft, installing newtonsoft directly fixed it.
> 
> Thanks @ryanzwe , this issue is already handled here : [https://github.com/Azure/azure-functions-core-tools/issues/3602](url)

Yikes.. New day, something new broken.. Seems we're all having fun working on newer azure functions :P

**Comment by cr3wdayt5p** [comment] 2024-02-21 12:07
I can confirm this happens when upgrading `Microsoft.Azure.Functions.Worker.Sdk` from `1.16.4` to `1.17.0`.

Details:
- .NET SDK 8.0.200
- func --version version 4.0.5530

**Comment by dustinrbb** [comment] 2024-03-05 14:04
Had this issue as well due to the same cause with `Microsoft.Azure.Functions.Worker.Sdk` version `1.17.0`. Looks like the latest version of the package resolves this issue though. Deleting the current bin/obj directories and then updating `Microsoft.Azure.Functions.Worker.Sdk` to `1.17.2` resolves this issue.

**Comment by per-samuelsson** [comment] 2024-03-27 13:44
I have `Microsoft.Azure.Functions.Worker.Sdk 1.17.2` and the latest tooling, `4.0.5611`. This issue persist.

Deleting `bin` and `obj` works as a workaround still.

**Comment by tiwilson7** [comment] 2024-04-12 14:38
We just upgraded to latest isolated functions with .net 8 and 4.0.5611 azure function core tools and are receiving the same issue.

The workarounds mentioned above work, but they are really annoying.

I will add that you can use the command line to clean and start at the same time, which makes it slightly less annoying.

```
dotnet clean & func start -p 1234
```

**Comment by alij** [comment] 2024-05-16 05:41
dotnet clean work around doesn't work for me as it doesn't remove the WorkerExtensions.csproj. I need to delete it manually for it to work:

rm {Path_To_Project}\obj\Debug\net8.0\WorkerExtensions\WorkerExtensions.csproj
func start --verbose

**Comment by akashkolaTap** [comment] 2024-05-31 13:48
Hi, I'm facing the same issue still. Is there any update on it?
Steps to reproduce:
![image](https://github.com/Azure/azure-functions-core-tools/assets/165397116/bb045943-6f07-4f9a-a64f-9cf37f85e3e1)

![image](https://github.com/Azure/azure-functions-core-tools/assets/165397116/d5755e5b-51e8-4912-824b-d6206d9a498f)

![image](https://github.com/Azure/azure-functions-core-tools/assets/165397116/b550cac8-09af-42c5-b8dc-a2699d42c29a)

Second time function start
![image](https://github.com/Azure/azure-functions-core-tools/assets/165397116/6aa63be0-11c4-4698-860f-860cc6ad632a)

**Comment by codebrane** [comment] 2024-06-06 06:56
This started with VSCode on Mac v1.90.0. There is no way to run anything from VSCode now, without first deleting the obj and bin folders to get rid of:

> Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2

> obj/Debug/net8.0/WorkerExtensions/WorkerExtensions.csproj
> ./TheProject.csproj

v1.90.0 also seemed to break SLN files as the project started using .vscode/launch.json in the root directory so it couldn't run from that either. Had to remove all SLN files to get it to the point where it fails with the above error.

**Comment by codebrane** [comment] 2024-06-07 06:25
To reproduce the issue:

- create new Azure Function App project using VSCode with HttpTrigger
- new project works fine and function app runs locally
- save project as workspace. SLN file appears in project directory.
- project is now unusable.

> /usr/local/share/dotnet/sdk/8.0.100/NuGet.targets(399,5): error MSB3202: The project file "/Users/alistair/dev/test/TestFunction/obj/Debug/net8.0/WorkerExtensions/WorkerExtensions.csproj" was not found. [/Users/alistair/dev/test/TestFunction/TestFunction.sln]

Existing projects and workspaces are fine. It's just workspaces created with this version of VSCode:

> Version: 1.90.0
> Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
> Date: 2024-06-04T19:34:44.157Z
> Electron: 29.4.0
> ElectronBuildId: 9593362
> Chromium: 122.0.6261.156
> Node.js: 20.9.0
> V8: 12.2.281.27-electron.0
> OS: Darwin x64 22.6.0
> 

**### Deleting the sln file resolves the issue but VSCode recreates it when opening the workspace and destroys the project.**

**Comment by FinOCE** [comment] 2024-06-12 00:41
Currently facing this issue as well. .net 8.0.301, func tools 4.0.5148, worker sdk 1.17.2, F# project. Deleting obj and bin workaround works but not dotnet clean. Any updates on a proper fix being made?

**Comment by HugoKNL** [comment] 2024-06-13 11:07
Happens for me with .net SDK 8.0.301, runtime 8.0.6 and func version 4.0.5801 and

**Comment by paulyuk** [comment] 2024-07-03 17:55
ACK I just filed this bug too and see this is a dupe.  I am escalating directly to team.

**Comment by albx** [comment] 2024-07-14 20:24
Same issue. 
In my case deleting the bin and obj folder solves the issue.

**Comment by binoypatel** [comment] 2024-07-17 20:27
same issue with func: 4.0.5907, it's not only annoying but waste of time since deleting obj will do the restore and compilation all over again, this has to be addressed sooner than later.

**Comment by MarksPoint** [comment] 2024-07-18 13:21
Same issue here! Of course, deleting bin and obj works, but this is no real solution as stated by others. Please fix, MS!

**Comment by dirkesquire** [comment] 2024-07-18 16:29
I don't wish to be mean, but I wonder who decided it would be a good idea to create \obj\Debug\net8.0\WorkerExtensions\WorkerExtensions.csproj on each build. I hope Azure Functions team seriously re-evaluates if this is indeed the route they want to be going in. I appreciate the hard work in separating out various workers, but there must be a better solution, surely. Perhaps this can be fixed in V5 on Azure Function Tools.

Error messages like:
`obj/Debug/net8.0/WorkerExtensions/WorkerExtensions.csproj" was not found` if .sln file is present (which gets automatically created)
Error messages like:
`Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2. ` if deleting the .sln file and running 'func start' twice in a row

It just seems such an anti-pattern (one .csproj project creating another .csproj project), and completely confuses everything. Solution (.sln) files being automatically created, needing to delete /bin and /obj folders on each run. VS Code now can't debug anymore. Azure pipeline broke since there are two projects detected. Azure functions just seems a complete mess now.
I must admit we are trying to upgrade from Azure Functions V1 which worked perfectly.

**Comment by davidgeary** [comment] 2024-07-19 09:08
FWIW (and as you'd probably expect), this is also a problem when running under Visual Studio 2022.  Similar to that described above, the easiest workaround appears to be to add `dotnet clean` to the project's _Post-build event_.

**Comment by TomJarFab** [comment] 2024-07-19 11:15
Still the same issue on version `Microsoft.Azure.Functions.Worker.Sdk 1.17.4`

**Comment by ryanski44** [comment] 2024-07-23 21:44
I've submitted a pull request with a fix to this issue. The fix limits the search for .csproj files to the function directory. It was recursively searching before. I think the fix is appropriate because the code in question is a validation check that is trying to make sure that a subsequent call to dotnet build is going to work, and dotnet build (when called without specifying a project file) also only looks in the working directory non-recursively. So, in my opinion the validation check should follow the same rules.

That being said, I'm not associated to this project in any way. I'm not a contributor to this project, nor do I work at Microsoft. I'm just someone who wanted this fixed. So, if you have one of the following questions, not only do I not know the answer, but I would also love to have an answer from a maintainer of this project.

- When will this pull request be reviewed?
- What release would this fix get included in?

I was able to build the project locally with my fix and then replace func.exe, func.dll in C:\Program Files\Microsoft\Azure Functions Core Tools with the ones I built and now the problem is fixed for me. You are welcome to attempt the same, but you would be on your own in terms of support, and there could be unexpected consequences of running a locally built version.

**Comment by kshyju** [comment] 2024-07-23 22:35
Thanks for your patience. We are working on a fix for this issue. 

Just to confirm, this issue is happening only for dotnet-isolated model function apps. Correct? If anyone else is seeing this issue in non-dotnet isolated apps, please share a minimal repro.

**Comment by FinOCE** [comment] 2024-07-24 04:48
> Thanks for your patience. We are working on a fix for this issue.
> 
> Just to confirm, this issue is happening only for dotnet-isolated model function apps. Correct? If anyone else is seeing this issue in non-dotnet isolated apps, please share a minimal repro.

I have a .net8 iso app that has this issue and a .net6 in-proc app that doesn't have it. Can't say for certain it doesnt happen on in-proc but at least on mine it doesn't.

**Comment by dirkesquire** [comment] 2024-07-24 11:36
I'm using .net 8 dotnet-isolated. 
For me it is the Worker.SDK that is borked.
Microsoft.Azure.Functions.Worker.Sdk - 1.16 - works
Microsoft.Azure.Functions.Worker.Sdk - 1.17.0, 1.17.1, 1.17.2, 1..17.3, 1.17.4 - borked

Personally I'd like to see the changes made in Worker.SDK 1.17.* rolled back

**Comment by reminvestor** [comment] 2024-07-24 15:32
> I'm using .net 8 dotnet-isolated. For me it is the Worker.SDK that is borked. Microsoft.Azure.Functions.Worker.Sdk - 1.16 - works Microsoft.Azure.Functions.Worker.Sdk - 1.17.0, 1.17.1, 1.17.2, 1..17.3, 1.17.4 - borked
> 
> Personally I'd like to see the changes made in Worker.SDK 1.17.* rolled back

I have the same issue with isolated .net 8 function I created from vs code on Mac. I set the project to use 1.16 and did a dotnet restore then ran the function again but I get this error.

Determining projects to restore...
  Restored /Users/ryan/Documents/Functions/Functions.csproj (in 282 ms).
  Functions -> /Users/ryan/Documents/Functions/bin/output/Functions.dll
  Determining projects to restore...
  Restored /var/folders/qv/9vgr49v90rn6739y_m8zjc6w0000gn/T/n5kakvcq.fvp/WorkerExtensions.csproj (in 897 ms).
  WorkerExtensions -> /var/folders/qv/9vgr49v90rn6739y_m8zjc6w0000gn/T/n5kakvcq.fvp/buildout/Microsoft.Azure.Functions.Worker.Extensions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.08



Azure Functions Core Tools
Core Tools Version:       4.0.5907 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit)
Function Runtime Version: 4.834.3.22875

[2024-07-24T15:27:56.297Z] Found /Users/ryan/Documents/Functions/Functions.csproj. Using for user secrets file configuration.
[2024-07-24T15:27:57.587Z] Worker process started and initialized.

Functions:

        QueueTrigger: QueueTrigger

For detailed output, run func with --verbose flag.
[2024-07-24T15:27:59.730Z] Worker process started and initialized.
[2024-07-24T15:27:59.736Z] Worker failed to load function: 'QueueTrigger' with functionId: '964268076'.
[2024-07-24T15:27:59.737Z] Result: Failure
[2024-07-24T15:27:59.737Z] Exception: System.InvalidOperationException: Unable to load Function 'QueueTrigger'. A function with the id '964268076' name already exists.
[2024-07-24T15:27:59.737Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
[2024-07-24T15:27:59.737Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
[2024-07-24T15:27:59.737Z] Stack:    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
[2024-07-24T15:27:59.737Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269.

**Comment by dzsquared** [comment] 2024-07-24 15:56
I think it may have something to do with the C# dev kit extension creating a sln automatically, not necessarily OS

**Comment by dirkesquire** [comment] 2024-07-24 17:25
@eminvestor are you sure you ran 'dotnet clean' and deleted your bin and obj folders before doing your test.
I am running 
`<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />`
and .net 8 isolated and do NOT get the problem. And yes I am also using VS Code for Mac, so that is not a problem.

I can verify that running 'find . -name "*.csproj"' returns only one .csproj file generated with Worker.Sdk.

The fact that you have 'WorkerExtensions.csproj' and errors like 'A function with the id '964268076' name already exists.', would indicate that you have old files hanging about from the 1.17 version of the Worker.SDK.

**Comment by jviau** [comment] 2024-07-24 20:40
#3773 aims to address this issue. The root problem is the cli is trying to recursively search for csproj's as a pre-validation for calling `dotnet build`. Instead, this validation can be removed entirely as `dotnet build` will perform its own validation.

**Comment by dirkesquire** [comment] 2024-07-25 09:48
Filtering out the second .csproj is actually not fixing the root problem, but more fixing a symptom of the problem.

The root cause is that versions 1.17 of the Worker.SDK are now producing WorkerExtensions.csproj, which it didn't before. This seems like an anti-pattern. One project generating another project on each and every build? It's a nightmare to debug, test and maintain. Sure you can 'filter' out the second .csproj but one still ends up with a bit of a code smell.

Running with Worker.SDK 1.16.4:
```
dotnet build
find . -name "*.csproj" 
```
Result:
./my-fn-project.csproj      (only the 1 .csproj of the project you are working on is found.)

Using Worker.SDK 1.17.0, 1.17.1, 1.17.2, 1.17.4:
```
dotnet build
find . -name "*.csproj"
```
Returns 
./obj/Debug/net8.0/WorkerExtensions/WorkerExtensions.csproj
./my-fn-project.csproj

Suddenly you can see a new WorkerExtensions.csproj created on EACH build from version 1.17.0 onwards.
That seems a bit weird and is going to make it so much harder to maintain the Azure Function code. It would be better code if it didn't create a project to create a dll, but just created the dll directly (like it did before).

What is the reason for WorkerExtensions.csproj? 
On my machine at least, WorkerExtensions.csproj seems to be targeting .net6.0:
`<TargetFramework>net6.0</TargetFramework>`
Which means another hidden subproject to maintain and which could go out of date. 

Going back to Worker.SDK 1.16.4 and everything just works, it has been a nice feeling.

**Comment by jviau** [comment] 2024-07-25 15:55
@dirkesquire the `WorkerExtension.csproj` is by design and will not be changing. The SDK has always been producing that project, just before it was placed in a new temp directory each build. We moved it to intermediate output directory so that the project's location is consistent between builds, allowing us to support incremental build.

This project is responsible for resolving the host extension payload to be included with the function app. We have discussed this design with the dotnet, msbuild, and nuget team. We all came to a conclusion there is no alternative to the generated project outside of re-implementing the entire assembly resolution system from the dotnet SDK - which is not a feasible approach.

**Closed** 2024-07-25 20:40 UTC
Labels: bug

**Comment by kshyju** [comment] 2024-07-25 21:14
Thanks to @ryanski44 for contributing the fix for this issue. We will provide an update in this thread when a new version of the core tools, including this change, becomes available.

**Comment by asolimaan** [comment] 2024-07-25 21:23
till you fix it i create this workaround 
-- in powershell
function runAzurFunc {
    # clean
    dotnet clean

    # build and run
    func start
}

Set-Alias -Name zfunc  -Value runAzurFunc

-- in mac
runAzurFunc() {
    # clean
    dotnet clean
    # build
    func start
}
alias zfunc=runAzurFunc

**Comment by mxa0079** [comment] 2024-07-28 19:44
> Thanks to @ryanski44 for contributing the fix for this issue. We will provide an update in this thread when a new version of the core tools, including this change, becomes available.

Is there an ETA?

I appreciate the effort, and in the spirit of providing good heart feedback I must say the the developer experience with Azure Functions in .NET has impacted my team's productivity -- to the point that we will not consider it as a viable architecture in the future and we will look for alternatives to migrate our code.

**Comment by claus18** [comment] 2024-07-30 09:50
For me this works fine with SDK 1.17.2  but fails when I upgrade Microsoft.Azure.Functions.Worker.Sdk to 1.17.4  (or 1.17.3)
We're on dotnet 8.0.303  
func version 4.0.5611 and using isolated mode  with multiple functions in same solution file. 

When starting from a the project directory
```
func start
Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2
```

Shouldn't the SDK 1.17.3 and 1.17.4  be removed from nuget, since they are causing so much trouble?
Even if you fix the tools version,  it is not good to have breaking change in the SDK that forces you to upgrade the Tools at the same time. 
Also I find it strange that this issue is "Closed"

**Comment by kpeek** [comment] 2024-08-15 19:52
Here's my workaround for VS Code on macOS - add a task to delete the bin and obj folders:

in tasks.json (important bit is task named `clean-bin-obj`):
```json
    {
      "label": "run-data-processing",
      "type": "func",
      "command": "host start --port 7071",
      "options": {
        "cwd": "${workspaceFolder}/data-processing"
      },
      "isBackground": true,
      "presentation": {
        "reveal": "always",
        "clear": true,
        "group": "data-processing",
        "revealProblems": "onProblem"
      },
      "problemMatcher": "$func-dotnet-watch",
      "dependsOn": ["clean-bin-obj"]
    },
    {
      // Cleans the bin and obj folders (hack to get around https://github.com/Azure/azure-functions-core-tools/issues/3594)
      "label": "clean-bin-obj",
      "type": "shell",
      "command": "find . -type d \\( -name \"bin\" -o -name \"obj\" \\) -exec rm -rf {} +",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "panel": "new"
      },
      "options": {
        "cwd": "${workspaceFolder}"
      }
    }
    ```

**Comment by PhilippRoessner** [comment] 2024-08-30 06:33
I have this issue in our .NET Aspire application. The workaround, deleting bin/obj, doesn’t work. I downgraded Microsoft.Azure.Functions.Worker.Sdk to 1.16.4, and I have this behavior with all the versions from 1.16.4 to the latest 1.17.4.

When I run the Azure function without .NET Aspire, it works fine.

Reading through these posts, I see that we are not alone in suffering from the horrible developer experience of Azure Functions. Our team works mostly with VS Code, and a little bit with Visual Studio. Both tools cannot even remotely offer the quality we are used to with other .NET technologies in development. “Blips” like this one will definitely get us to reevaluate our architecture design regarding serverless technologies.

**Comment by dsschnau** [comment] 2024-08-30 20:05
I upgrade to version 4.0.5907, and I still have this problem. It's annoying :/

**Comment by dirkesquire** [comment] 2024-08-31 12:36
It's clear that the team or individuals who decided it was a good idea to role out this switch to the .csproj file locations did not do proper testing before releasing this. I think Microsoft needs to up their game on cross platform testing. Please hire me!

**Comment by alemag1986** [comment] 2024-09-01 02:08
macOS Sonoma 14.6.1
dotnet version 8.0.401
azure-functions-core-tools@4 4.0.5907

@dsschnau  @dirkesquire Issue still active in version 4.0.5907
The code change from the merged PR is not in the latest release [https://github.com/Azure/azure-functions-core-tools/blob/4.0.5907/src/Azure.Functions.Cli/Common/FileSystemHelpers.cs](4.0.5907)

The fix is here [https://github.com/Azure/azure-functions-core-tools/pull/3773](#3773)

Pretty annoying... I have lots of issues with Azure Functions on net8 in the last month or so...since net6 is going away.

**Comment by rkacel** [comment] 2024-09-04 16:18
for me this behaviour went away when I disabled the Extension : C# dev Kit;  Option : Dotnet Automatically Create Solution In Workspace

**Comment by ReluXingZeng** [comment] 2024-09-09 02:11
Running into the same issue in 5907 in a debian linux container

our container is based on `mcr.microsoft.com/dotnet/sdk:8.0` which is pretty official...

full in-container specification:
```
vscode@91376dec6507:/workspaces/priviq-workflow-service$ func --version
4.0.5907
vscode@91376dec6507:/workspaces/priviq-workflow-service$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
vscode@91376dec6507:/workspaces/priviq-workflow-service$ dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.204/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by alemag1986** [comment] 2024-09-09 02:44
Cleaning the nuget cache fixed everything. 
- `nuget locals all -clear`

**Comment by chsami** [comment] 2024-09-13 14:34
> Delete the /bin & obj folder

Thanks for the solution, lost quite some time on this...

**Comment by kshyju** [comment] 2024-09-16 14:31
A new version or core tools was released last week with a fix to address this issue. Please upgrade to that version.
 
 https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.6280

**Comment by AllenConway** [comment] 2025-02-26 00:36
Note - this error can also occur and be a bit of a red herring if you haven't yet installed the Azure Functions Core Tools. I was switching between dev boxes, assumed I had already installed it, started researching this error, and low and behold I had not yet installed the toolset yet. Once installed, I stopped getting that error using `func start`

Might of been better if the error alerted me as such that the tool chain was missing, but manifested itself as, "Expected 1 .csproj or .fsproj but found 2..."
