### ISSUE TITLE
VS 2017 is not upgrading functions CLI

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-functions-core-tools#694] opened 2018-09-05 11:33 UTC
(VS 2017 15.7.5)
(VS "Azure Functions and Web Jobs Tools" extension 15.10.2009.0)

When I launch my project in debug VS, it begins downloading "Azure Functions CLI 1.3.0". I see network traffic but I'm not sure where it's saved. `%LOCALAPPDATA%\AzureFunctionsTools\Releases\1.3.0` exists but remains empty.

The project actually launches in CLI 1.0.10, from `%LOCALAPPDATA%\AzureFunctionsTools\Releases\1.0.10`

This is a Functions 1.x project, which CLI release should I be using? (1.0.12?)

Also, how do I stop it downloading 1.3.0 over and over?

**Comment by Ryanman** [comment] 2018-09-05 15:06
Having the same issue with 2.5.1 . VS attempts to install the new version of the CLI, Creates the folder but does not add anything to it.

When the functions spin up eventually they point to the 2.3.2 folder and I get this error:

`8 3:04:17 PM] A ScriptHost error has occurred
[9/5/2018 3:04:17 PM] System.Private.CoreLib: No parameterless constructor defined for this object.
[9/5/2018 3:04:17 PM] Stopping Host
Function host is not running.`

Any way to install the later versions of the CLI manually (Since I assume it just looks in the latest folder with func.exe?)

**Comment by ahmelsayed** [comment] 2018-09-17 19:27
@soninaren Can you take a look

**Comment by soninaren** [comment] 2018-09-17 22:47
@ishepherd and @raymondb1, Looks like the download is not happening cleanly for you guys. 
To mitigate this issue:
1. Close all instances of VS
2. Delete this folder %LOCALAPPDATA%\AzureFunctionsTools
3. Delete %USERPROFILE%\.templateengine
4. Open Visual Studio -> File -> New Project -> Select `Azure Functions` -> You should see loading at the bottom
![image](https://user-images.githubusercontent.com/8119379/45654534-d831cf00-ba90-11e8-8863-3582896497a9.png)
5. Wait for it to finish, Open your existing project. 

@ishepherd, After this it should not download 1.3.0 over and over again.

**Comment by ishepherd** [comment] 2018-09-19 10:29
@soninaren Thanks

> Making sure all templates are up to date...

this stage never completes.
It has created,

```
%LOCALAPPDATA%\AzureFunctionsTools\Releases
    \1.0.10
    \1.0.11   << Empty
    \1.3.0   << Empty
    \2.0.1-beta.25
    \2.0.1-beta.26   << Empty
```

Please allow a couple of days and I will retest this process on a different internet connection, I have my doubts about my home connection.

**Comment by JohnReeson** [comment] 2018-09-20 01:59
@soninaren Met [same problem](https://github.com/Azure/Azure-Functions/issues/807) before. Downloading may fail due to network problem and falls back to use 1.0.10 and 2.0.1-beta.25 shipped with VS extension. Could the cli shipped with extension be updated, so that when some of us met network issue, we can still leverage cli which is not so old?

**Comment by soninaren** [comment] 2018-09-20 17:14
@JohnReeson, yes i will follow up with the VS team to make sure an updated version of cli is shipped with next version of VS extension. Will also follow up to see if we sort out the download issue.

You can get the contents of Azure Functions Tools folder here: https://funcstore01.blob.core.windows.net/download/AzureFunctionsTools.zip

Make sure you delete the `%USERPROFILE%\.templateengine` folder before you start VS.

**Comment by ishepherd** [comment] 2018-09-21 00:07
@soninaren @JohnReeson I repeated [those steps](https://github.com/Azure/azure-functions-core-tools/issues/694#issuecomment-422196447) today, on a better network connection. Works now and my project launches in 1.3.0.

This is a very "unusual" way to surface a network problem :) So yes please look at it.

----

Releases dir now looks like
```
%LOCALAPPDATA%\AzureFunctionsTools\Releases
    \1.0.11
    \1.3.0
    \2.0.1-beta.26
    \2.8.0
```

**Comment by JohnReeson** [comment] 2018-11-29 07:21
Issue can be closed. Duplicate of [this closed one](https://github.com/Azure/azure-functions-host/issues/3759).

**Comment by soninaren** [comment] 2018-11-30 00:07
@ishepherd this is definitely something we are tracking and would make improvements to . We have done some work to reduce the download size and have a [wiki page](https://github.com/Azure/azure-functions-tooling-feed/wiki/Fixing-Azure-Function-Core-Tools-download-issues-for-Visual-Studio#execute-an-automated-script) to help resolve the issue.

**Closed** 2018-11-30 00:07 UTC
