### ISSUE TITLE
Support using Azurite

### ISSUE THREAD

**Issue by danabdn** [Azure/azure-functions-core-tools#1200] opened 2019-04-14 10:29 UTC
**Hello,**

_Version: 2.5.553
Environment: VSCode
Commands: VSCode terminal / CMD
When: func start
Project details: 1 http trigger (worked fine with no errors), 1 timer trigger (problems start)_

**Problem**
I have a timer function using Azurite as the local store (rather than standard emulator database which failed to create so switched to Azurite).
I have been receiving an error (see below).  
In all honesty, I am not sure if this is Core Tools or Azurite that is a problem.
There may be some configuration of my PC which is the cause and would welcome any suggestions.  SO not revealing any other instances of this error.

```
[14/04/2019 10:00:00] Executed 'my-order-scanning' (Succeeded, Id=c74e86f9-3125-4621-a69d-f0b8f181498d)
[14/04/2019 10:00:36] Error writing logs to table storage: Microsoft.WindowsAzure.Storage.StorageException: Not Implemented
[14/04/2019 10:00:36]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
[14/04/2019 10:00:36]    at Microsoft.Azure.WebJobs.Logging.Utility.SafeExecuteAsync(CloudTable table, TableBatchOperation batch) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\Utility.cs:line 179
[14/04/2019 10:00:36]    at Microsoft.Azure.WebJobs.Logging.Utility.WriteBatchAsync[T](ILogTableProvider logTableProvider, IEnumerable`1 e1) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\Utility.cs:line 269
[14/04/2019 10:00:36]    at Microsoft.Azure.WebJobs.Logging.LogWriter.FlushTimelineAggregateAsync(Boolean always) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\LogWriter.cs:line 265
[14/04/2019 10:00:36]    at Microsoft.Azure.WebJobs.Logging.LogWriter.FlushCoreAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\LogWriter.cs:line 316
[14/04/2019 10:00:36] Request Information
[14/04/2019 10:00:36] RequestID:
[14/04/2019 10:00:36] RequestDate:Sun, 14 Apr 2019 11:00:36 GMT
[14/04/2019 10:00:36] StatusMessage:Not Implemented
[14/04/2019 10:00:36] ErrorCode:
[14/04/2019 10:00:36]
```

**Expected**
No errors - full implementation

**Other information**
I couldn't get Azure storage emulator to work due to missing forward slash in the database creation code for the database but they said upgrading to Azurite would fix issue.  Therefore may be less likely to do with back end.  Can there be something about a PC name/network that confuses file paths?
[Issue #871](https://github.com/Azure/azure-storage-net/issues/871)

Host.json
```
{
    "version": "2.0"
}
```

local.settings.json
```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "AzureWebJobsDashboard": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet",
        "ASPNETCORE_ENVIRONMENT": "development"
    },
    "Host": {
        "LocalHttpPort": 7071,
        "CORS": "*"
    },
    "ConnectionStrings": {
        "SQLConnectionString": "Server=XXXXX\\SQLEXPRESS;Database=XXXX;Trusted_Connection=True;"
    }
}
```

When using storage explorer to view the queue, I can see queue entries in there.
00000000000010142520-XXXX-
(where XXXX is my pc name - single word - letters only)
Should the queue name end in hyphen?  Is this indicative of an issue?  Grasping at straws probably. 

**Thanks,
Dan.**

**Comment by danabdn** [comment] 2019-04-14 13:50
**Update - the following line is the cause of the issue - no errors if removed**

` "AzureWebJobsDashboard": "UseDevelopmentStorage=true"`

Am I using something that has is obsolete?  I'm currently just after a HTTP trigger and a Timer trigger.
I should mention both of those are working even with the exception.

**Thanks,
Dan.**

**Comment by ahmedelnably** [comment] 2019-04-16 22:55
Can you please provide the Storage SDK version, and the Storage emulator version

**Comment by danabdn** [comment] 2019-04-17 20:20
WindowsAzure.Storage: 9.3.1
Azurite: 2.7.0

Windows Azure Storage Emulator: 5.7.0.0 (but not using because the database won't create - see issue linked in main issue description).

**Comment by ahmedelnably** [comment] 2019-04-23 18:20
Thanks @danabdn, we currently do not support using Azurite with the Core Tools, we will work on adding the support in the future. I will change the title of the issue to "Support using Azurite" and will update the issue when we have the support.

**Comment by JustinGrote** [comment] 2019-05-03 00:39
This is an Azurite issue, in that the "normal" request is made to Azurite and Azurite responds that it hasn't implemented that feature.

If you're working locally you don't really need to write logs to table storage because you see them in output, so to use Azurite to do things like test queues/timers/etc. so just disable it in your local.settings.json like this:

```
func settings delete AzureWebJobsDashboard
func settings add AzureWebJobsStorage "useDevelopmentStorage=$true"
```

AzureWebJobsDashboard is just used for logging to view in the "monitor" tab, you don't care about that for Core Tools, you should be disabling this in production and using Application Insights instead anyways :)

**Comment by ahmedelnably** [comment] 2019-12-11 22:53
Closing as duplicate of #1247

**Closed by ahmedelnably** 2019-12-11 22:53 UTC
Labels: feature
