### ISSUE TITLE
Cannot access a disposed object. Object name: 'IServiceProvider'.

### ISSUE THREAD

**Issue by danilovulovic** [Azure/azure-functions-core-tools#1903] opened 2020-03-19 11:26 UTC
When I try to run Azure function in the local environment, I get this error:

![image](https://user-images.githubusercontent.com/1795248/77062576-6e271c80-69dc-11ea-9f2b-bfa67d1cad35.png)

I get the same error if I try to use v2.

I already checked all those issues:

https://github.com/Azure/azure-functions-host/issues/4521
https://github.com/Azure/azure-functions-host/issues/4520

Also, I have tried to reinstall Visual Studio and update to the latest version of Azure Function Core Tools.

This issue appears if I run a function app via Visual Studio 2019 or from the command line using **func host start**. I have tried to set a different port numbers as well.

Does someone have a solution to this issue?

**Comment by danilovulovic** [comment] 2020-03-19 18:36
I figured out VS starts x64 version and it can cause the problem. When I download func-cli-3.0.2358-x86.msi, set up debug for the project, it works.

How can I set VS to run x86 cli?

**Comment by anthonychu** [comment] 2020-03-19 23:42
@soninaren Do you know what might be happening here?

**Comment by soninaren** [comment] 2020-03-21 02:38
Not sure why you are getting service disposed exception because of x64. We would need more information to find the root cause. However Visual studio does provide configuration to use x86 version of core tools instead of x64. You need to set environment variable AZURE_FUNCTIONS_PREFER32BIT=1. It is supported by Visual studio 2019 16.5.0 and higher.

Also note that after setting this environment variable it will not trigger any download immediately. It will download x86 of core tools when there is an update. You can trigger a download by
1. Closing all versions of VS
2.  go to `%userprofile%\AppData\Local\AzureFunctionsTools\Releases`
3. delete the highest release version of VS you see.
4. Start VS again.

This should cause VS to download new version of core tools which should be x86. Also Note if you have low bandwidth the download could take sometime.

**Comment by danilovulovic** [comment] 2020-03-22 08:22
@soninaren Thank you for the help. This resolved issues.

Which information do you need for x64 version in order to figure out what is the problem. For me, x86 is enough, but maybe someone else need x64.

**Comment by soninaren** [comment] 2020-03-23 21:36
@danilovulovic a standalone repro would be the best thing here. If not then the content of csproj file and host.json would help as well. 
Also do you get this error even when you remove all functions and plainly start the function app. It would be good to isolate which function is causing this error.

**Comment by danilovulovic** [comment] 2020-03-25 11:05
It happens even with new Azure function app with simple Http trigger function.

I'm not sure is it related to this error, but I had issues with Xamarin app as well and figured out I had non-latin character in Users path: C:\Users\DaniloVulović.

I have completely reinstalled the system and set user path to C:\Users\DaniloVulovic and everything work as expected: Azure Functions, Xamarin,...

So maybe this can help someone.

**Comment by soninaren** [comment] 2020-03-25 23:30
For some reason i could not repro the issue with non-latin character. Going to close the issue now.

**Closed by soninaren** 2020-03-25 23:30 UTC
Labels: investigate
