### ISSUE TITLE
Error Importing dependecy MicrosoftTeams module above v3.*

### ISSUE THREAD

**Issue by alessiodecastro** [Azure/azure-functions-core-tools#2973] opened 2022-03-02 14:00 UTC
Hi, I have an Azure Function Powershell the function is in production and is correctly using commands belonging to the imported module requirement:
```
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    'MicrosoftTeams' = '2.*'
}
```

We need to use new PS Teams commands available from the version 3.0.0 so after changing the requirements.psd1 with the following and redeploying the function:
```
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'.
    'MicrosoftTeams' = '3.*'
}
```
We receive the following trace, seems like it is trying to download the new version but get error:
```
2022-03-02T13:36:26  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2022-03-02T13:37:49.841 [Information] Executing 'Functions.HttpTriggerTest' (Reason='This function was programmatically called via the host APIs.', Id=43f38b60-f050-4e08-9051-13e8d42d3ff3)
2022-03-02T13:37:56.477 [Warning] The first managed dependency download is in progress, function execution will continue when it's done. Depending on the content of requirements.psd1, this can take a few minutes. Subsequent function executions will not block and updates will be performed in the background.
2022-03-02T13:38:24.665 [Error] Executed 'Functions.HttpTriggerTest' (Failed, Id=ce955a0a-89a5-4387-a48a-62b38ad34ed6, Duration=120283ms)Result: FailureException: Failed to install function app dependencies. Error: 'Failed to install function app dependencies. Error: 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to save the module 'MicrosoftTeams'.''Stack:    at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitOnDependencyInstallationTask() in /home/vsts/work/1/s/src/DependencyManagement/DependencyManager.cs:line 248at Microsoft.Azure.Functions.PowerShellWorker.DependencyManagement.DependencyManager.WaitForDependenciesAvailability(Func`1 getLogger) in /home/vsts/work/1/s/src/DependencyManagement/DependencyManager.cs:line 165at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 253
```
The MicrosoftTeams module is available from the PS gallery as the v2.* the PS core version used is 7.0 
![image](https://user-images.githubusercontent.com/10231253/156375942-9fc239ca-a023-4e92-918d-5b5362e2d7d3.png)

Thanks

**Comment by michaelpeng36** [comment] 2022-03-08 18:50
Closing, as this issue is a duplicate of [this issue](https://github.com/Azure/azure-functions-powershell-worker/issues/771).

**Closed by michaelpeng36** 2022-03-08 18:50 UTC
Labels: Needs: Triage :mag:
