### ISSUE TITLE
Core tool release question

### ISSUE THREAD

**Issue by amamounelsayed** [Azure/azure-functions-core-tools#2162] opened 2020-08-20 01:30 UTC
Is there any future plans to releases core tools before releasing runtime?

This can give the customer the ability to test the next release, and validate the runtime failure (have the ability to recreate the issues locally if it happens on prod)

**Comment by IanKemp** [comment] 2020-09-04 09:03
Dupe of #2122 I think?

**Comment by apawast** [comment] 2020-09-22 18:19
Closing as duplicate of #2122

**Closed by apawast** 2020-09-22 18:19 UTC
Labels: Needs: Discussion
