### ISSUE TITLE
Coretools not honoring the --authlevel param

### ISSUE THREAD

**Issue by gavin-aguiar** [Azure/azure-functions-core-tools#3555] opened 2023-12-15 18:21 UTC
I tried created a python function app with the following command

` func new --name HttpExample --template "HTTP trigger" --authlevel "ANONYMOUS"`
 
and it prompted me to select the auth level

![image](https://github.com/Azure/azure-functions-core-tools/assets/80794152/3e54a9e3-5c6a-4f2c-a1f6-371bfa9e81bd)

Looks like the func new command is not parsing the `--authlevel` param

**Comment by ggailey777** [comment] 2023-12-15 18:58
Can confirm this command works correctly for Node.js v4.

**Comment by khkh-ms** [comment] 2024-02-01 18:19
Duplicate of https://github.com/Azure/azure-functions-core-tools/issues/3470

**Comment by khkh-ms** [comment] 2024-02-01 23:42
Fix has been merged and will be released on few weeks.

**Closed by khkh-ms** 2024-02-01 23:42 UTC
Labels: bug, Triaged
