### ISSUE TITLE
Remove virtual environment requirement 

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1138] opened 2019-03-21 20:51 UTC

**Comment by ankitkumarr** [comment] 2019-03-25 15:33
@asavaritayal, this looks like a duplicate of https://github.com/Azure/azure-functions-core-tools/issues/1023https://github.com/Azure/azure-functions-core-tools/issues/1023 which was closed by https://github.com/Azure/azure-functions-core-tools/pull/1095. It should be available in the next release.

**Closed** 2019-03-25 22:50 UTC
Labels: P1, language:Python, milestone:GA
