### ISSUE TITLE
Func new does not prompt user and displays error on Mac (v2.0.12438.0)

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-core-tools#1313] opened 2019-05-15 21:10 UTC
This issue was reported by a customer.

Repro steps:
```
host.json content:
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
}

func new
```

Expected: UI prompts user for template options
Actual: Error message displays
```
Value cannot be null.
Parameter name:value
```

If the extensionBundle entry is removed, the CLI works as expected. 
```
host.json content for which the CLI does not throw.
{
    "version": "2.0"
}
```

**Comment by prabhat00155** [comment] 2019-05-15 21:19
I get this error when I use this host.json(mentioned in the documentation):
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }   
}

**Comment by soninaren** [comment] 2019-05-15 21:42
@Francisco-Gamino and @prabhat00155 which version of core tools are you running. This was resolved in `https://github.com/Azure/azure-functions-core-tools/releases/tag/2.7.1158`

**Comment by Francisco-Gamino** [comment] 2019-05-15 22:52
@soninaren : @prabhat00155 is using the latest version v2.0.12438.0. This turned out to be a doc issue. I am waiting from @prabhat00155 for confirmation on the steps he followed. After that, I will open a doc issue and close this one.

**Comment by ankitkumarr** [comment] 2019-05-17 07:13
@Francisco-Gamino / @prabhat00155 , `v2.0.12438.0` is the Functions Runtime Version (that core-tools uses). You'd want to verify that `Azure Functions Core Tools` version is `2.7.1158`.

```
Azure Functions Core Tools (2.7.1158 Commit hash: f2d2a2816e038165826c7409c6d10c0527e8955b)
Function Runtime Version: 2.0.12438.0
```

I tried with `v2.7.1158`, and was unable to reproduce. I am closing the issue, please re-open if you continue to see errors.

**Closed by ankitkumarr** 2019-05-17 07:13 UTC
Labels: Needs: Triage :mag:
