### ISSUE TITLE
Returning an HTTP response with array in 2.7.1505 serializes incorrectly

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-functions-core-tools#1478] opened 2019-08-07 02:22 UTC
**Version**: 2.7.1505

After upgrading azure function core tools to latest version returning an HTTP response with an array incorrectly serializes to `System.Collections.Generic.List``1[System.Object]`

To reproduce set one of the following with a Node HTTP trigger:

`context.res = {
  body: [],
  status: 200
};
`

or

`context.done(null, {
  body: [],
  status: 200,
});`

It appears that this same version is now deployed out to azure as well effecting our production instances.

**Comment by mhoeger** [comment] 2019-08-14 23:41
Root cause is this issue: https://github.com/Azure/azure-functions-nodejs-worker/issues/228

The reason why there appeared to be a regression is because we accidentally released a fix for this bug (that has always existed) in a version of the core-tools. Although it is a bug to return “System.Collections.Generic…”, the fix that was briefly released (only in the core-tools) will cause a breaking change in behavior to all apps running in production that take a dependencies on the existing, buggy behavior.

Fix tracked for 3.x in issue above

**Closed by mhoeger** 2019-08-14 23:41 UTC
Labels: Needs: Triage :mag:
