### ISSUE TITLE
OFFSET LIMIT not supported for cross-partition cosmosDB collections

### ISSUE THREAD

**Issue by probablyup** [Azure/azure-functions-core-tools#1929] opened 2020-04-09 18:10 UTC
When executing a query using the JSON CosmosDB input:

```json
{
      "type": "cosmosDB",
      "direction": "in",
      "name": "waitlistEntries",
      "databaseName": "waitlist",
      "collectionName": "waitlist",
      "connectionStringSetting": "[redacted]",
      "sqlQuery": "SELECT * FROM c WHERE c.status = \"QUEUED\" OR c.status = \"REQUEUED\" ORDER by c.queuePosition ASC OFFSET 0 LIMIT 1"
},
```

I receive this error:

```
Executed 'Functions.waitlist_invite' (Failed, Id=9ebba5c3-37c3-4e37-86cf-a3ff03c9ba83)
[4/9/2020 6:05:26 PM] System.Private.CoreLib: Exception while executing function: Functions.waitlist_invite. Microsoft.Azure.DocumentDB.Core: Cross Partition OFFSET / LIMIT is not supported.
```

However, the query runs as expected in the Azure Portal Data Explorer and several issues on the topic (and the documentation) appear to indicate this query _is_ supported.

**Comment by anthonychu** [comment] 2020-04-12 21:05
Looks like a duplicate of https://github.com/Azure/azure-webjobs-sdk-extensions/issues/621. Please use that issue to track this. Thanks!

**Closed by anthonychu** 2020-04-12 21:05 UTC
Labels: Needs: Triage :mag:

**Comment by probablyup** [comment] 2020-04-24 14:24
@anthonychu Could we get this reopened please? Support for this functionality was released in the webjobs extension last week but it's still not working through the `func` CLI here. https://github.com/Azure/azure-webjobs-sdk-extensions/releases/tag/cosmos-v3.0.6

**Comment by probablyup** [comment] 2020-04-24 14:56
Nvm https://github.com/Azure/azure-functions-extension-bundles/pull/20
