### ISSUE TITLE
Incorrect Functions core tools installation with chocolatey packages 

### ISSUE THREAD

**Issue by raorugan** [Azure/azure-functions-core-tools#2851] opened 2021-12-02 10:15 UTC
The command choco install azure-functions-core-tools 2 and choco install azure-functions-core-tools both install v 3.0.3442 but choco install azure-functions-core-tools 3 installs v4.0.3928

**Comment by ejizba** [comment] 2021-12-02 19:41
Duplicate of https://github.com/Azure/azure-functions-core-tools/issues/2807

**Closed by ejizba** 2021-12-02 19:41 UTC
Labels: Needs: Triage :mag:
