### ISSUE TITLE
3.0.2852 Utilities.cs

### ISSUE THREAD

**Issue by petesanderson** [Azure/azure-functions-core-tools#2187] opened 2020-09-02 09:32 UTC
Following an auto-update of the tools, myself and a number of my team are unable to run.

![image](https://user-images.githubusercontent.com/10696106/91964602-3f410080-ed07-11ea-8224-fb535e906c55.png)

This is the exception trace:
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=func
  StackTrace:
   at Azure.Functions.Cli.Utilities.LogLevelExists(IConfigurationRoot hostJsonConfig, String category) in D:\a\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 208`

![image](https://user-images.githubusercontent.com/10696106/91964769-7a433400-ed07-11ea-857c-79ddc1d2db11.png)

Thanks.

**Comment by djmrky** [comment] 2020-09-02 10:27
Same here, it suddenly stopped working ... any workarounds?

**Comment by hasandogu** [comment] 2020-09-02 10:30
We have the exact same issue. 

Interesting thing is, it starts if we set the function project as the Startup Project but not when we select Multiple Startup Projects from the solution.

Tried setting the LogLevel as instructed [here](https://github.com/Azure/azure-functions-core-tools/issues/2184#issuecomment-685383715) but didn't help.

**Comment by hasandogu** [comment] 2020-09-02 10:35
I have just changed the order of the projects and made the function project to start before all the others and it started working.

**Comment by djmrky** [comment] 2020-09-02 10:49
It just started working again, I'm not sure what happened

**Comment by GrigorescuNicolae** [comment] 2020-09-02 10:56
Have you changed anything?

**Comment by petesanderson** [comment] 2020-09-02 10:57
> I have just changed the order of the projects and made the function project to start before all the others and it started working.

Great suggestion - that's worked for us - I would've never have thought of that. We also commonly have multiple startup projects.

**Comment by GrigorescuNicolae** [comment] 2020-09-02 11:06
>  started working again, I'm not sure what happened

Have you changed anything?
>  I have just changed the order of the projects and made the function project to start before all the others and it started working.

I only have 1 startup project and still get that error. Any other idea is welcomed.

**Comment by djmrky** [comment] 2020-09-02 12:06
I had it as a single project start and then I went into multiple project startup and set only this one project to start and it worked. Then I returned it to how it was (single project start) and it continued to work ... very strange

**Comment by djmrky** [comment] 2020-09-02 13:21
This was not the solution, after restarting the machine, it's not working again ... no debug

**Comment by anthonychu** [comment] 2020-09-02 14:14
Looks like a duplicate of #2183

**Comment by pragnagopa** [comment] 2020-09-02 14:37
Closing as this a dup.

**Closed by pragnagopa** 2020-09-02 14:37 UTC
Labels: Needs: Triage :mag:
