### ISSUE TITLE
func azure functionapp publish <app-name> returning 401 (Unauthorized)

### ISSUE THREAD

**Issue by Invigor** [Azure/azure-functions-core-tools#822] opened 2018-10-24 02:14 UTC
Hi all,

I'm trying to create  Python based Azure function using the following instructions:
- https://github.com/Azure/azure-functions-python-worker/wiki/Create-your-first-Python-function
- https://github.com/Azure/Azure-Functions/wiki/Azure-Functions-on-Linux-Preview

Everything is working fine including running the function locally but when I try to publish the function app project to Azure  with environment variable CLI=1 I get the following:
```
michael@azure-functions-vm:~/SpotLiteEbaySearchProj$ func azure functionapp publish ebay-search
> az account get-access-token --query "accessToken"
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions?api-version=2014-04-01
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload)
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken)
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync()
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container)
```
The function app (ebay-search) was created via the CLI and I can see it in the Azure portal.
I've gone through the az login step and I should be the owner of the function app.
I've tried using the most recent beta release but get the same issue.

Any advice will be appreciated!

Thanks,

Michael

**Comment by astaykov** [comment] 2018-11-12 11:49
Me too.
Although I see very interesting and different results based on the name I use:

```
(env) root@f3b3b1d27ee0:/hostlink/PythonFnApp# CLI_DEBUG=1 func azure functionapp fetch-app-settings fa-preview-python
> az account get-access-token --query "accessToken"
GET https://management.azure.com/subscriptions?api-version=2018-09-01
GET https://management.azure.com/subscriptions?api-version=2018-09-01
{"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}
GET https://management.azure.com/subscriptions?api-version=2018-09-01
{"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}
GET https://management.azure.com/subscriptions?api-version=2018-09-01
{"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 219
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 23
   at Azure.Functions.Cli.Actions.AzureActions.FetchAppSettingsAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\FetchAppSettingsAction.cs:line 24
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
(env) root@f3b3b1d27ee0:/hostlink/PythonFnApp#

```
and

```
(env) root@f3b3b1d27ee0:/hostlink/PythonFnApp# CLI_DEBUG=1 func azure functionapp publish fa-preview-python.azurewebsites.net
> az account get-access-token --query "accessToken"
GET https://management.azure.com/subscriptions?api-version=2018-09-01
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'xxxxxx' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'yyyyy' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'zzzzz' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'wwwwww' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'vvvv' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'aaaaa' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'bbbbb' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'ccccc' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'ddddd' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'eeeee' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&%24filter=(SubscriptionId+eq+%fffff%27+and+name+eq+%27fa-preview-python.azurewebsites.net%27+and+resourceType+eq+%27Microsoft.Web%2fsites%27)&%24skiptoken=asdf%2fiafdj38%3d
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'asdf' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'asdf' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'asdf' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'asdf' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId eq 'asdf' and name eq 'fa-preview-python.azurewebsites.net' and resourceType eq 'Microsoft.Web/sites')
Azure.Functions.Cli.Arm.ArmResourceNotFoundException: Can't find app with name "fa-preview-python.azurewebsites.net"
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken)
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 115
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
(env) root@f3b3b1d27ee0:/hostlink/PythonFnApp#
```

Completely confusing results ...
I am the owner of the function app, created via CLI tools....

**Comment by r3dlin3** [comment] 2019-01-03 21:49
I was able to reproduce the problem with .Net Core SDK 2.2.
After uninstalling 2.2 and installing 2.1, I was able to publish.

```
func -V
2.3.199

azure-cli (2.0.54)
```

**Comment by simonjaeger** [comment] 2019-02-01 12:01
Can confirm this issue is happening. Please see the deployment steps at: https://docs.microsoft.com/en-us/azure/azure-functions/create-function-app-linux-app-service-plan

This is also referred to in the docs repository: https://github.com/MicrosoftDocs/azure-docs/issues/23227

Azure Functions Core Tools (2.4.299 Commit hash: 0f105e9bc6e2faed71e8521d7541a909a6dcc389)
Function Runtime Version: 2.0.12285.0

**Comment by roalexan** [comment] 2019-02-15 20:45
I am hitting this issue as well - which is a real blocker, BTW. I did not hit this originally because I ran the steps from the above mentioned link as-is. However, I now want to hook up an identity for my app, and the portal indicates that identities are not supported for "consumption plans" (when I try to create an identity from the CLI, BTW, it just returns a 400 bad request). So, I created a Linux app service (in a new resource group) and replaced --consumption-plan-location <your location> with -- plan <your plan>, and now I hit this issue.

**Comment by asavaritayal** [comment] 2019-02-16 03:03
This is a know issue being tracked here - https://github.com/Azure/azure-cli/issues/8553

Workarounds:

Option 1- Create the app using portal. Rest of the commands should work from CLI.
 
Option 2 - Specify the right image explicity when using the CLI. Add --deployment-container-image-name azure-functions-python3.6:2.0 to the create command

**Comment by roalexan** [comment] 2019-02-19 19:42
Unfortunately I was not able to get either workaround to work.

For Option 1, I created the Linux app service and function app from the portal. When I ran 'func azure functionapp publish rbatest3functionapp' it hanged at this console output line:
Uploading 74.72 MB [##############################################################################]
I eventually cancelled out, and verified from the portal that the functions were not added.

for Option 2, I specified the deployment container image name as suggested, and this time got a different console output message:
Uploading 74.72 MB [##############################################################################]
Upload completed successfully.
Response status code does not indicate success: 400 (Bad Request)

**Comment by roalexan** [comment] 2019-02-20 17:47
Below are the steps on a Windows laptop I used to reproduce. This assumes that you have the prerequisites: Python 3.6, Azure Function Core Tools, .NET Core 2.x SDK for Windows, and Node.js.

open: command prompt
type:
	set SUBSCRIPTION_ID=[your subscription id]
	set RESOURCE_GROUP=[your resource group]
	set STORAGE_ACCOUNT=[your storage account]
	set APP_PLAN=[your app plan]
	set FUNCTION_APP=[your function app]
	py -3.6 -m venv .env
	.env\scripts\activate
	func init %FUNCTION_APP%
select: python (preview)
type:
	cd %FUNCTION_APP%
	func new
select: HTTP trigger
type:
	EchoName
	func host start # test locally, e.g.: http://localhost:7071/api/EchoName?name=john
	az login
	az account set --subscription %SUBSCRIPTION_ID%
	az account show
	az group create --name %RESOURCE_GROUP% --location eastus
	az storage account create --name %STORAGE_ACCOUNT% --location eastus --resource-group %RESOURCE_GROUP% --sku Standard_LRS
	az appservice plan create -g %RESOURCE_GROUP% -n %APP_PLAN% --is-linux --number-of-workers 4 --sku S1
	az functionapp create --resource-group %RESOURCE_GROUP% --os-type Linux --plan %APP_PLAN% --runtime python --name %FUNCTION_APP% --storage-account %STORAGE_ACCOUNT% --deployment-container-image-name azure-functions-python3.6:2.0
	func azure functionapp publish %FUNCTION_APP%

**Comment by ankitkumarr** [comment] 2019-02-27 00:27
@roalexan, thank you for sharing the exact steps. That does help a lot.

for Option 2, `--deployment-container-image-name azure-functions-python3.6:2.0` should be `--deployment-container-image-name microsoft/azure-functions-python3.6:2.0`. Sorry about that.

However, you may still see the hanging bit (as in Option 1) once you fix that. I will investigate that part and report back.

**Comment by ankitkumarr** [comment] 2019-02-27 00:39
@roalexan, could you retry with the latest `azure-functions-core-tools` creating the function app in the portal? That actually seemed to work for me.

Uploading 74.72 MB [#############################################################################]
 can take a few seconds, but shouldn't be too long.

Let me know if that does not work out. For using the `azure-cli`, I have the PR up. In the next release or so, it should be fixed.

**Comment by roalexan** [comment] 2019-02-27 15:47
Thanks for the follow-up. My findings:

I updated to the latest azure-function-core-tools (2.4.401). I then re-ran "option 2" from above using "microsoft/azure-functions-python3.6:2.0" as the deployment container image name. Console output:

Uploading 72.52 MB [##############################################################################]
Upload completed successfully.
Functions in <FUNCTION APP>:

So, no functions listed, but no failure output either. I went to the portal, and didn't see any functions there either. Doesn't work, but that's to be expected, I assume, since you have a PR in the works for the CLI.

For "option 1" from above, that did work! I created the function app on the portal, then uploaded the function. Output as follows:

Uploading 72.52 MB [##############################################################################]
Upload completed successfully.
Functions in rbatest4functionapp:
    EchoName - [httpTrigger]
        Invoke url: http://<FUNCTION APP>.azurewebsites.net/api/echoname

Looks good. The only thing missing is the code needed to authenticate - I think I remember previously I saw the code from the console output. Anyway, I could get code from the portal and verify the REST call works.

**Comment by ankitkumarr** [comment] 2019-02-27 19:15
Thanks for the report!

> The only thing missing is the code needed to authenticate - I think I remember previously seeing the code from the console output

Do you mean the auth key for the function API? If so, the invoke url is supposed to show the key if your auth is not set to `"anonymous"`. You can check your auth settings in the `function.json`, the key is called `"authLevel"` in the `"bindings"` list. If you need function level auth, you can set it to `"function"`.

Additionally you can use `func azure functionapp list-functions` to view the functions and the URLs. You can pass `--show-keys` to this and it will list the URLs with the appropriate key(s) if applicable.

**Comment by ankitkumarr** [comment] 2019-03-01 02:22
Closing this issue as the the error was caused by a bug in the Azure CLI which should be fixed by https://github.com/Azure/azure-cli/pull/8645. Please reopen if you continue to see issues on functionapps created from future releases of the Azure CLI.

**Closed by ankitkumarr** 2019-03-01 02:22 UTC
Labels: language:Python
