### ISSUE TITLE
Typescript: No connection established

### ISSUE THREAD

**Issue by tech-run** [Azure/azure-functions-core-tools#3018] opened 2022-04-07 03:48 UTC
Hi All 
I'm New to azure-function-core-tools package. 
 
Created a basic off MS site however unable to launch Azure Function as the following error occured (No connection established). The  Azure Function is coded within Node as a Typescript Application.  
local.setting.json displayed below. 

```
Azure Functions Core Tools
Core Tools Version:       4.0.4426 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473

[2022-04-07T03:38:29.421Z] Configured Uri (http://127.0.0.1:20124/) does not match actual Uri (http://127.0.0.1:20055/).

Functions:

        MyHttpTrigger: [GET,POST] http://localhost:7071/api/MyHttpTrigger

For detailed output, run func with --verbose flag.
[2022-04-07T03:38:30.979Z]     at Object.t.callErrorFromStatus (C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:40625)
[2022-04-07T03:38:30.982Z]     at Object.onReceiveStatus (C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:66215)
[2022-04-07T03:38:30.991Z]     at Object.onReceiveStatus (C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:58583)
[2022-04-07T03:38:30.993Z]     at C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:31694
[2022-04-07T03:38:31.001Z]     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[2022-04-07T03:38:31.374Z]   code: 14,
[2022-04-07T03:38:31.419Z]   details: 'No connection established',
[2022-04-07T03:38:31.420Z]   metadata: u { internalRepr: Map(0) {}, options: {} }
[2022-04-07T03:38:31.421Z] }
[2022-04-07T03:38:31.422Z]     at Object.t.callErrorFromStatus (C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:40625)
[2022-04-07T03:38:31.423Z]     at Object.onReceiveStatus (C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:66215)
[2022-04-07T03:38:31.424Z]     at Object.onReceiveStatus (C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:58583)
[2022-04-07T03:38:31.426Z]     at C:\dev\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:2:31694
[2022-04-07T03:38:31.439Z]     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[2022-04-07T03:38:31.443Z]   code: 14,
[2022-04-07T03:38:31.444Z]   details: 'No connection established',
[2022-04-07T03:38:31.449Z]   metadata: u { internalRepr: Map(0) {}, options: {} }
[2022-04-07T03:38:31.449Z] }
```

local.setting.json file: 
```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "NO_PROXY": "localhost,0.0.0.0,127.0.0.1"
  }
}
```

**Comment by michaelpeng36** [comment] 2022-04-07 21:22
@tech-run Are you doing something to alter `localhost` on your machine? It seems the first line `[2022-04-07T03:38:29.421Z] Configured Uri (http://127.0.0.1:20124/) does not match actual Uri (http://127.0.0.1:20055/).` may be related to the root cause of your issue.

**Comment by tech-run** [comment] 2022-04-11 20:43
> @tech-run Are you doing something to alter `localhost` on your machine? It seems the first line `[2022-04-07T03:38:29.421Z] Configured Uri (http://127.0.0.1:20124/) does not match actual Uri (http://127.0.0.1:20055/).` may be related to the root cause of your issue.

I've checked hosts file and removed all references to localhost. However no sucess.  I have an IIS server running however have stopped this while trying to start Function Tools. Whe the function app starts is creates a SCNoification process with a Sub process of Background IntelligentTransferService.

**Comment by aiden-liu** [comment] 2022-05-09 03:38
Is there any solution yet? Cause I'm having the same issue, with no proxy and running inside a VM. 
Version info as below:
- func: 4.0.4483
- node: v16.14.0
- typescript: 4.6.4

**Comment by tech-run** [comment] 2022-05-09 03:57
> Is there any solution yet? Cause I'm having the same issue, with no proxy and running inside a VM. Version info as below:
> 
> * func: 4.0.4483
> * node: v16.14.0
> * typescript: 4.6.4

Unfortunately just setup a new VM.

**Comment by apawast** [comment] 2022-05-12 20:02
@aiden-liu are you still experiencing this issue? Have you tried setting up a new VM?

**Comment by aiden-liu** [comment] 2022-05-13 11:56
New VM is fine, although without knowing why

**Comment by michaelpeng36** [comment] 2022-06-15 16:55
Closing this issue, as we are unable to reproduce the error, and it looks like this issue may be specific to the user's VM setup.

**Closed by michaelpeng36** 2022-06-15 16:55 UTC
Labels: Needs: Attention :wave:
