### ISSUE TITLE
How to get the verbosity of previous versions back?

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-core-tools#2200] opened 2020-09-04 09:19 UTC
I know most people have asked for a way to make `func.exe` **less** verbose, but I was pretty happy with its verbosity. It seems like the latest release (3.0.2881 / runtime 3.0.14287.0) has made it less verbose when run from Visual Studio - which would not be an issue, if (a) this had been recorded in the release notes (b) the release notes provided a way to get the old behaviour back.

When `func.exe` is run from VS, it suggests "For detailed output, run func with --verbose flag." But adding `--verbose` in the Project properties > Debug > Application arguments textbox doesn't allow `func.exe` to start as expected.

I also tried adding the following to `local.settings.json` as per https://github.com/anthonychu/functions-log-suppression:

```json
{
  "logging:logLevel:Microsoft": "Debug",
  "logging:logLevel:Worker": "Debug",
  "AzureFunctionsJobHost:logging:logLevel:default": "Debug",
  "AzureFunctionsJobHost:logging:logLevel:Host.Function.Console": "Debug"
}
```

but that does not change the output either.

1. Please advise how I can get the old "super-verbose" behaviour of `func.exe` back when run from Visual Studio
1. Please update the release notes to state this behaviour change
1. Please add the information from (1) into the release notes

**Comment by sh3ll** [comment] 2020-09-04 12:11
Yes, agree, I have seen that change yesterday and been thinking that maybe I have switched something. For me would be useful to have back full `--verbose` on output. Hopefully it will come with next update.

**Comment by IanKemp** [comment] 2020-09-04 12:40
> Yes, agree, I have seen that change yesterday and been thinking that maybe I have switched something. For me would be useful to have back full `--verbose` on output. Hopefully it will come with next update.

The bigger issue for me is that the team should not be changing things that affect users, without informing users first. It's made worse by the fact that Visual Studio will always force you to use the latest version of the tools. At the very least, when VS updates the tools, it should also open a web page to the release notes - and those release notes should include information about changes like this.

**Comment by anthonychu** [comment] 2020-09-04 15:20
@IanKemp Take a look at this to enable verbose logs in VS: https://github.com/Azure/azure-functions-host/issues/6582#issuecomment-685207874

We’ll look into a way to adjust this globally on your machine (perhaps with an environment variable or config). What logs are missing that you’d like to see again? Our goal is to reduce verbosity of system logs but maintain the same level of user logs.

Good feedback on release notes. I think we can do better here.

**Comment by klenium** [comment] 2020-09-04 17:27
My previous `host.json`:
```
{
  "logging": {
    "logLevel": {
      "Microsoft.EntityFrameworkCore": "None"
      "Function.ManualRunner.User": "Information",
      "Function": "Error"
    }
  }
}
```
This was totally fine for me. Now the console seems to ignore the EFC config, making the output unreadable. I randomly lost all ability to see real logs. Please never do that. If there is a working configuration, why change that? If you use new format, provide a way to convert, or show a message about the change, and describe what we need to do.

**Comment by IanKemp** [comment] 2020-09-08 16:02
> @IanKemp Take a look at this to enable verbose logs in VS: [Azure/azure-functions-host#6582 (comment)](https://github.com/Azure/azure-functions-host/issues/6582#issuecomment-685207874)

That did the trick, thanks! Please just make sure it makes it into those mythical release notes...

> My previous `host.json`:
> 
> ```
> {
>   "logging": {
>     "logLevel": {
>       "Microsoft.EntityFrameworkCore": "None"
>       "Function.ManualRunner.User": "Information",
>       "Function": "Error"
>     }
>   }
> }
> ```
> 
> This was totally fine for me. Now the console seems to ignore the EFC config, making the output unreadable. I randomly lost all ability to see real logs. Please never do that. If there is a working configuration, why change that? If you use new format, provide a way to convert, or show a message about the change, and describe what we need to do.

As per [@anthonychu's comment](https://github.com/Azure/azure-functions-host/issues/6582#issuecomment-685207874), add `start --verbose` to your function project's properties > Debug > Application arguments.

**Comment by klenium** [comment] 2020-09-08 16:08
@IanKemp If I don't want EntityFrameworkCore to print anything, I need to add a flag for printing messages more verbosely? This makes no sense. That might be a solution for the old `Function.XXX` configs, but there are other cases too. I had to set `default` to `Error` to calm down EFC.

**Comment by anthonychu** [comment] 2020-09-08 16:54
@klenium You’re right. The intent of the recent changes was to suppress some of the noisier logs from the host by default, but there should be no changes to user logs and any log levels specified by the user should be respected. We’ll make further changes to address this.

**Comment by IanKemp** [comment] 2020-09-08 16:55
Reopening so that it can be closed when the issue @klenium is having with EF is resolved.

**Comment by klenium** [comment] 2020-09-08 16:59
Thank you, looking forward for updates.

**Comment by m-sterspace** [comment] 2020-09-26 16:20
Yeah, another voice for wanting the verbosity changed back. We've had to revert back to previous versions of core tools because suddenly all of our javascript `console.log` statements are no longer outputting anything.

**Comment by anthonychu** [comment] 2020-09-27 21:54
@m-sterspace Sorry about that. `console.log` output should be back in the next release, hopefully out in the next week or so.  If you would like to get it before it's released to the official channels, you can download it from [here](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2931).

/cc @pragnagopa

**Comment by pragnagopa** [comment] 2020-09-28 15:40
Issues mentioned here should be fixed in release: https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2931 - this will be released sometime this week.

Apologies for the unintended regression that was introduced around logging filters. PR #2223  has addressed this regression.

Closing as addressed. Please use the drop pointed by @anthonychu until we release Core-Tools to all the tooling.

**Closed by pragnagopa** 2020-09-28 15:40 UTC
