### ISSUE TITLE
App Service Plan / Linux / Python / uuid library deployment

### ISSUE THREAD

**Issue by E-HO** [Azure/azure-functions-core-tools#2863] opened 2021-12-06 19:12 UTC
Hi,

I'm encountering a blocking issue while trying to deploy a solution using: 
- Azure Functions on a Standard "App Service Plan",
- under Linux for Python (Runtime version or Python version don't make a difference, however tested first with ~4 and 3.9)
- any pip library using the standard "uuid"

**### Way to reproduce:** 
- Create a project using VS Code and Azure functions Core tools
- Create a simple Http trigger with the default code, set "uuid" in requirements, import uuid in __init__.py and change the HttpResponse with something like uuid.uuid1 to generate it.
- Visibly during the deployment there is NO errors shown.
- Copy URL and try to connect (was using Function Auth code), it takes time and page is blank.
- **Issue 1 :** Go to the logs (Monitor / Logs on the portal) to see a message with "Did not find any initialized language workers"
- **Issue 2 :** Also deeper in the logs of the "Host", another different message is showing "
> [Information] if not 0 <= time_low < 1<<32L:
> [Information] ^
> [Error] SyntaxError: invalid syntax

Thanks,

**Comment by michaelpeng36** [comment] 2021-12-07 18:35
@E-HO , do you have this app in a public repository? @vrdmr @fabiocav this seems like either a Python worker or Host issue. Could you help with this?

**Comment by E-HO** [comment] 2021-12-07 22:10
Hi,

No specific project is made, since a simple line of code from the default "HTTP Trigger" is enough to create the problem.
This issue don't occurs locally or in others projects who don't use App Services and Azure Functions ... so indeed i think it's more an issue on the worker or on the hosts (there are 2 different errors logs for them).

Thanks,

**Comment by E-HO** [comment] 2021-12-28 09:07
Hi @vrdmr , @fabiocav ,

Any news on this bug submitted 3 weeks ago ? I made others tests but it remains a blocking point.

Regards,

**Comment by fabiocav** [comment] 2022-01-28 14:30
@E-HO thank you for the follow up!

@michaelpeng36 did you repro this? With a repro, the goal would be to isolate the language worker failure that is leading to this condition. @vrdmr we may have to sync on this to look at the worker failure.

Will follow up with folks pinged on this thread, but also flagging this for triage review.

@liliankasem it would be good to understand whether you've captured anything as part of the diagnostic enhancements effort that will help better surface the error details here. If not, let's run through the scenario and make sure we have something planned.

@E-HO we'll continue to provide updates here as we make progress. Thank you for the patience!

**Comment by michaelpeng36** [comment] 2022-01-28 20:29
@fabiocav Yes, I was able to reproduce this issue. As @E-HO mentioned, it took some time to connect, eventually resulting in a failure, and I see the following in the Monitor Logs:
```
Final functionDispatcher state: WorkerProcessRestarting. Initialization timed out and host is shutting down
```
and
```
Did not find any initialized language workers
```

**Comment by liliankasem** [comment] 2022-01-28 22:08
@michaelpeng36 can you share the repro with me, I'd like to use it to help better surface logs for issues like this!

**Comment by vrdmr** [comment] 2022-01-29 08:13
@liliankasem I've sent an update internally to detail the issue. 

This is due to a standard library being added as a requirement and conflicting with the worker dependency.

ref ICM: 279492292

**Comment by vrdmr** [comment] 2022-01-30 04:49
Apologies for the delay.

The core issue is 

> _Create a simple Http trigger with the default code, set "uuid" in requirements, import uuid in init.py and change the HttpResponse with something like uuid.uuid1 to generate it._

UUID is already a system library (UUID — UUID objects according to RFC 4122) and doesn't need to be added as a separate requirement in the requirements.txt.

**Mitigation: remove UUID from requirements.txt and redeploy**

The fundamental issue is that as UUID is being added as a separate requirement when starting the worker, it breaks the worker's loaded system libraries and doesn't start it.

**Comment by fabiocav** [comment] 2022-02-09 21:52
Thank you, @vrdmr . Closing this as answered/resolved, but please let us know if you have any additional questions.

**Closed by fabiocav** 2022-02-09 21:52 UTC
Labels: Needs: Triage :mag:, Needs: Attention :wave:
