### ISSUE TITLE
How to manage shared code

### ISSUE THREAD

**Issue by NVolcz** [Azure/azure-functions-core-tools#1987] opened 2020-05-13 19:54 UTC
I have a bunch of Azure Python Function Apps that share some code and is not sure how I am sure how this is supposed work. The shared code is proprietary and cannot be uploaded to PyPi. My issue is similar to: https://github.com/Azure/azure-functions-python-worker/issues/219

This is how I would like the folder structure to look like:
```
AzureFunctions
|_ FunctionApp1
    |_ requirements.txt
    |_ HttpTrigger1
        |_ __init__.py
        |_ function.json
|_FunctionApp2
    |_ requirements.txt
    |_ HttpTrigger1
        |_ __init__.py
        |_ function.json
|_ SharedCode
    |_ setup.py
    |_ requirements.txt
    |_ src
        |_ __init__.py
        |_ common1.py
        |_ common2.py
    |_ tests
        |_ test1.py
        |_ test2.py
```

I have tried to use the `file:` protocol in FunctionApp1 and FunctionApp2's requirements.txt:
`file:../SharedCode`
Most tooling understands this except for `pip freeze`. Skipping the `file:` part also seems works well with other tooling but neither does not work well with `func`. Remote build and `--build-native-deps` cannot build these function apps since they do not get access to the SharedCode folder, only the functions individual folders. I have therefor tried to build locally. It seems like the first problem with this lies with the packapp script: https://github.com/Azure/azure-functions-core-tools/blob/dev/tools/python/packapp/__main__.py#L73-L79
This SO thread seems related: https://stackoverflow.com/questions/11147667/is-there-a-way-to-list-pip-dependencies-requirements
pip download outputs this:
```
Processing <PATH>/AzureFunctions/SharedCode
    Link is a directory, ignoring download_dir
```

What should I do?

**Comment by zsolt-halo** [comment] 2020-05-14 08:19
Did you take a look at [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#import-behavior)?

It works for me. Not very clear as the comments say so but once you figure out the example it will work.

**Comment by NVolcz** [comment] 2020-05-15 06:53
The difference between function apps and functions is confusing to say the least (and there are no such things on the other platforms). The above example "works" but is not ideal. We wanted separate function apps for separate managed identities. Also, how many functions can fit in a functions app? We currently have four but are planning to add many more and without the possibility to share code between functions apps all with end up in the same function app. In an ideal world I would not like to manage the function app at all.

**Comment by apawast** [comment] 2021-11-09 15:52
@NVolcz are you still experiencing this issue?

**Comment by NVolcz** [comment] 2021-11-09 23:48
We gave up on trying to use Python with Azure Functions after not receiving any help on this issue. 
Have you changed anything?

**Comment by maximeLeurent** [comment] 2021-11-10 07:09
@NVolcz Did you see my answer? 
`Have you changed anything?` => If the question was for me, no I didn't, i implement the way I describe.

**Comment by apawast** [comment] 2021-11-12 18:59
Closing as duplicate of https://github.com/Azure/azure-functions-host/issues/5373. The Python team is working on a new programming model.

**Closed by apawast** 2021-11-12 18:59 UTC
Labels: Needs: Attention :wave:
