### ISSUE TITLE
Every `functionapp` sub-command result in "Invalid URI: The URI scheme is not valid." error

### ISSUE THREAD

**Issue by wisaTong** [Azure/azure-functions-core-tools#2824] opened 2021-11-09 17:21 UTC
I created a simple function app with `func init` `func new` and then tried to publish it with `func azure functionapp publish myapp` and got "Invalid URI: The URI scheme is not valid." as an output.

output of `CLI_DEBUG=1 func azure functionapp publish myapp`
```
> az account get-access-token --query "accessToken" --output json
> az cloud list --query "[?isActive].endpoints.resourceManager | [0]" --output json
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Azure.Functions.Cli.Helpers.AzureHelper.GetSubscriptions(String accessToken, String managementURL) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 295
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken, String managementURL, String slot, String defaultSubscription, IEnumerable`1 allSubs) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 33
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 133
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

`fetch-app-settings`, `list-functions`, and `logstream` also give similar output.

**Comment by wisaTong** [comment] 2021-11-10 03:44
I think I know what my problem is. The `--query` flag for my az CLI doesn't work, so the output was messed up. But I still can't figure out why my `--query` flag does nothing.

**Comment by wisaTong** [comment] 2021-11-10 14:47
This issue might be the root cause https://github.com/Azure/azure-cli/issues/20269

**Comment by apawast** [comment] 2021-11-10 23:50
@wisaTong thanks for pointing out the CLI issue. Is okay to close this issue as a duplicate of that one?

**Comment by wisaTong** [comment] 2021-11-11 02:47
Sure, please do.

**Closed** 2021-11-11 16:46 UTC
Labels: Needs: Attention :wave:
