### ISSUE TITLE
func start [cannot create shared memory usage: /dev/shm/AzureFunctions]

### ISSUE THREAD

**Issue by sayantikabanik** [Azure/azure-functions-core-tools#2758] opened 2021-10-11 05:20 UTC
**Issue**
- I followed the steps from the documentation to get started with the creation of a simple azure function and encountered the following errors/warnings

<details>

<summary> Logs </summary>

```python
[2021-10-08T07:21:41.983Z] Cannot create directory for shared memory usage: /dev/shm/AzureFunctions
[2021-10-08T07:21:41.986Z] System.IO.FileSystem: Access to the path '/dev/shm/AzureFunctions' is denied. Operation not permitted.
[2021-10-08T07:21:43.251Z] Traceback (most recent call last):
[2021-10-08T07:21:43.254Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 50, in main
[2021-10-08T07:21:43.254Z]     return aio_compat.run(start_async(
[2021-10-08T07:21:43.254Z]   File "/Users/sayantikabanik/miniforge3/lib/python3.9/asyncio/runners.py", line 44, in run
[2021-10-08T07:21:43.254Z]     return loop.run_until_complete(main)
[2021-10-08T07:21:43.254Z]   File "/Users/sayantikabanik/miniforge3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
[2021-10-08T07:21:43.254Z]     return future.result()
[2021-10-08T07:21:43.254Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/azure_functions_worker/main.py", line 58, in start_async
[2021-10-08T07:21:43.254Z]     from . import dispatcher
[2021-10-08T07:21:43.254Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/azure_functions_worker/dispatcher.py", line 19, in <module>
[2021-10-08T07:21:43.254Z]     import grpc
[2021-10-08T07:21:43.254Z]   File "/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/grpc/__init__.py", line 23, in <module>
[2021-10-08T07:21:43.254Z]     from grpc._cython import cygrpc as _cygrpc
[2021-10-08T07:21:43.256Z] ImportError: dlopen(/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so, 2): no suitable image found.  Did find:
[2021-10-08T07:21:43.257Z] 	/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so: mach-o, but wrong architecture
[2021-10-08T07:21:43.257Z] 	/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3785/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so: mach-o, but wrong architecture
```
</details>

**Version/machine  info**
- azure-functions-core-tool
```shellscript 
brew info azure-functions-core-tools@3
azure/functions/azure-functions-core-tools@3: stable 3.0.3785, HEAD
Azure Functions Core Tools 3.0
```
- macOS `arm64`
- python version `3.9`

**Command used - reproducing the above error**
`func start`

**Similar issues reported- external links**
- [396617 :MS community]( https://docs.microsoft.com/en-us/answers/questions/396617/azure-functions-core-tools-error-osx-devshmazurefu.html)

**Comment by apawast** [comment] 2021-10-12 17:51
Duplicate of #2600

**Closed** 2021-11-03 03:00 UTC
Labels: duplicate
