### ISSUE TITLE
func azure functionapp - Response status code does not indicate success: 400 (Bad Request)

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-functions-core-tools#788] opened 2018-10-10 10:48 UTC
When I run any `func azure functionapp` command I get a 400 error

Here is the output with **CLI_DEBUG=1** set

```func azure functionapp logstream myfuncapp
> az account get-access-token --query "accessToken"
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions?api-version=2014-04-01
GET https://management.azure.com/subscriptions?api-version=2014-04-01
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload)
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken)
   at Azure.Functions.Cli.Actions.AzureActions.LogStreamAction.RunAsync()
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container)
```

**Comment by benc-uk** [comment] 2018-10-10 11:12
I've tried removing my **.azure** and **.azurefunctions** directories and I get prompted to authenticate with `az login` which I do, but the problem remains

**Comment by ahmelsayed** [comment] 2018-10-15 22:11
I can't quite figure out what's happening from the logs on the backend. I see the request to list subscriptions is getting a 401, but I'm not sure why. I added more logging in the CLI and updated the API version used for listing subscriptions.

**Comment by ahmelsayed** [comment] 2018-10-15 22:14
Closing this since it's a duplicate of https://github.com/Azure/azure-functions-core-tools/issues/778 Will keep the other one updated until I can get a bit more logs.

**Closed by ahmelsayed** 2018-10-15 22:14 UTC
Labels: 2.2.x, help wanted

**Comment by burkeholland** [comment] 2018-11-06 18:20
Any update on this issue?

**Comment by ahmelsayed** [comment] 2018-11-06 19:52
Can you update to the current version and run the same command with `CLI_DEBUG=1` and share the output? I added more logging since then but haven't seen or heard back on the issue.
