### ISSUE TITLE
Identify language worker when performing func new

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-core-tools#1886] opened 2020-03-09 17:48 UTC
Steps to Reproduce:

- In Visual Studio Code, create a new Python Function app (func new --name MyEventHubTriggerFuncCoreTools --template AzureEventHubTrigger --language Python)

- Notice no requirements.txt file is created

- Attempt to publish via Azure Function Core Tools (func azure functionapp publish mypythonapp)

- Notice an error: "requirements.txt is not found. requirements.txt is required for python function apps. Please make sure to generate one before publishing."

The issue was that `func init` wasn't performed but this is not intuitive through this workflow. So its best to warn the user to initialize the language worker. Else this can be resolved by creating requirements.txt, but the actual issue is that func core tools is not aware of what language worker the user intended to use and should prompt that question.

**Comment by anthonychu** [comment] 2020-03-10 18:15
Thanks @priyaananthasankar. It's a duplicate of #1259. We'll track this there.

**Closed by anthonychu** 2020-03-10 18:15 UTC
