### ISSUE TITLE
Azure Functions Tools Release 2.18.4 Breaks Dependency Injection 

### ISSUE THREAD

**Issue by jzoss** [Azure/azure-functions-core-tools#1151] opened 2019-03-25 21:02 UTC
I was automatically updated  to Azure Functions Tools Release 2.18.4 today. I have been using Automapper with Azure Functions, with no problems. However after visual studio automatically updated to tools version 2.18.4 Automapper DI now fails.  When I manually tricked vs to use the old version 2.18.3, the exception is fixed.. 

When running 2.18.3 these are the versions I get on start up

![image](https://user-images.githubusercontent.com/3586254/54953796-1663eb80-4f17-11e9-8e1e-f56e3a19168f.png)

and 2.18.4

![image](https://user-images.githubusercontent.com/3586254/54953883-47dcb700-4f17-11e9-9ac4-e2169d4ba1b1.png)

and I now get a error 'Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'AutoMapper.IMapper' while attempting to activate '....'

**Comment by mahic** [comment] 2019-03-26 08:12
We experience this as well. There seems to be a breaking change or a bug in the `2.4.498` version. Running manually with `func start` with the `2.4.419` version of the [NPM package](https://www.npmjs.com/package/azure-functions-core-tools) also works.

**Comment by fabiocav** [comment] 2019-03-26 18:50
@jzoss this is a result of a regression introduced with the last release of the host and tools. The fix has been made and it is currently rolling out to azure. A Core Tools release will take place when that deployment completes.

**Comment by mahic** [comment] 2019-03-26 19:11
@fabiocav Could you please link the appropriate commits to this issue and resolve when the deploy and new Core Tools are in place?

**Comment by rhythmnewt** [comment] 2019-03-26 19:59
Any ETA on the core tools release?

**Comment by jzoss** [comment] 2019-03-26 21:29
@fabiocav Awesome news, Thanks for the quick fix.

**Comment by pb-qs** [comment] 2019-03-27 08:04
Hi - any ETA on the Core Tools fix, or a workaround ?

**Comment by rhythmnewt** [comment] 2019-03-27 16:37
When is the fix going to be rolled out? Can we somehow downgrade the tools in visual studio?

**Comment by mronnlun** [comment] 2019-03-28 07:36
@fabiocav Any update on this? This is halting our development at the moment

**Comment by miantosca** [comment] 2019-03-28 14:43
same here

**Comment by fabiocav** [comment] 2019-03-28 16:39
Yes, the fix is rolling out to Azure and once the deployment completes there, the Core Tools targeting that host will be released. We expect that to happen at the end of the week.

**Comment by rhythmnewt** [comment] 2019-03-28 17:30
@fabiocav how can we roll back to previous version of tools? Our development effort is stuck.

**Comment by miantosca** [comment] 2019-03-28 17:56
> @fabiocav how can we roll back to previous version of tools? Our development effort is stuck.

from Jaffacakes82: If you're still having the issue I did the following to resolve npm install -g azure-functions-core-tools@2.4.419 and ensure your launch settings are executing this host. I had multiple installations of the core tools for some reason.

**Comment by rhythmnewt** [comment] 2019-03-28 19:31
@miantosca I tried that but even though I'm getting the right version on load, the DI still doesn't work. now I'm totally confused.

Globally installed core tools version
```
+-- azure-functions-core-tools@2.4.419
```

Launch settings
```
  "LocalFunctionsCLI": {
      "commandName": "Executable",
      "executablePath": "dotnet.exe",
      "commandLineArgs": "%userprofile%\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\bin\\func.dll host start"
    }
```

Console output
```
Azure Functions Core Tools (2.4.419 Commit hash: c9c1724d002bd90b2e6b41393915ea3a26bcf0ce)
Function Runtime Version: 2.0.12332.0

```

**Comment by fabiocav** [comment] 2019-03-28 21:52
Exactly... there are some details here as well: https://github.com/Azure/app-service-announcements-discussions/issues/85#issuecomment-476382217

**Comment by pb-qs** [comment] 2019-03-29 10:04
> Hi - any ETA on the Core Tools fix, or a workaround ?

Version 2.18.5 now installed and DI working again.  Thanks @fabiocav et al.

**Comment by rhythmnewt** [comment] 2019-03-29 16:32
Updated to latest tools, looking good. Thanks for quick turnaround!

**Comment by miantosca** [comment] 2019-03-29 16:45
> Updated to latest tools, looking good. Thanks for quick turnaround!

which version? I don't see a newer one than the one from 3-days ago 2.4.498

**Comment by miantosca** [comment] 2019-03-29 18:38
I see 2.5.553 in the releases. How long before they show up npm? I downloaded the zip - are there instructions on installing from the zip?

**Comment by rhythmnewt** [comment] 2019-04-01 18:04
I updated the tools through Visual Studio update tools command.

Azure Functions Core Tools (2.5.553 Commit hash: b63f2d6f5479718ca276f7b585a8cc6b9bc57c4f)
Function Runtime Version: 2.0.12382.0

**Comment by ankitkumarr** [comment] 2019-04-04 21:10
`azure-functions-core-tools@2.5.553` should be released in all supported package managers (including `npm`). 

Closing this issue. Please re-open if you continue to see issues.

**Closed by ankitkumarr** 2019-04-04 21:10 UTC
