### ISSUE TITLE
Incorrect DOTNET Runtime used / No Assemblies Found

### ISSUE THREAD

**Issue by cawoodm** [Azure/azure-functions-core-tools#4127] opened 2024-10-24 06:58 UTC
### Version

4.0.6518

I have other functions working fine with version 4.1036.1.23224 but I see no way of telling my project which version to use.

The .csproj has `<AzureFunctionsVersion>v4</AzureFunctionsVersion>` whilst `host.json` has `"version": "2.0"`

### Description

As described in detail [here](https://stackoverflow.com/questions/79117563/vs-project-cannot-load-find-any-assemblies) I have a C# project which will not run or rather func.exe/dll is unable to start the project due to missing assemblies. In this case it cannot find a single .net assembyl which leads me to believe it is using the wrong .NET runtime - I think it's trying to use .NET v6 for some reason although this is a .NET v8 project.

In the log it says "Loading .NET 6 host" though I never see this configured anywhere and .NET 6 is not installed.

To be honest it's extremely confusing and instransparent how these versions interrelate and also why we have `func.exe`, `func.dll` and even NPM packages `func.cmd` installed all over.

```
[2024-10-24T06:45:22.320Z] [CoreToolsHost] Starting CoreToolsHost
[2024-10-24T06:45:22.322Z] [CoreToolsHost] Loading .NET 6 host
[2024-10-24T06:45:22.322Z] [CoreToolsHost] File path to load: C:\Users\YYY\AppData\Local\AzureFunctionsTools\Releases\4.99.0-inprocess\cli_x64\in-proc6\func.dll
[2024-10-24T06:45:22.323Z] [CoreToolsHost] hostfxr path:C:\Users\YYY\AppData\Local\AzureFunctionsTools\Releases\4.99.0-inprocess\cli_x64\in-proc6\hostfxr.dll
[2024-10-24T06:45:22.324Z] [CoreToolsHost] hostfxr loaded.
[2024-10-24T06:45:22.342Z] [CoreToolsHost] hostfxr initialized with C:\Users\YYY\AppData\Local\AzureFunctionsTools\Releases\4.99.0-inprocess\cli_x64\in-proc6\func.dll

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.0.6518 Commit hash: N/A +74ed9095fdd6c5326276aae6b8a7d41ccbdeb6aa (64-bit)
Function Runtime Version: 4.35.4.23179

[2024-10-24T06:45:25.710Z] Found C:\projects\XXX\ZZZ\logic\XXX.AAA\XXX.AAA.csproj. Using for user secrets file configuration.
[2024-10-24T06:45:28.600Z] Error configuring services in an external startup class.
[2024-10-24T06:45:28.603Z] Error configuring services in an external startup class. XXX.AAA: Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
[2024-10-24T06:45:28.850Z] A host error has occurred during startup operation '6700af0a-a04d-45a7-8b33-a180a2fff785'.
[2024-10-24T06:45:28.858Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. XXX.AAA: Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
Press any key to continue....[2024-10-24T06:45:30.027Z] Error configuring services in an external startup class.
[2024-10-24T06:45:30.028Z] Error configuring services in an external startup class. XXX.AAA: Could not load file or assembly 'System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

### Steps to reproduce

I cannot reproduce this issue is other projects - it is one project here (closed source) which has the issue.
New Azure Functions Projects work fine though they are using a different func version which, again, I see no way of specifying.

![Image](https://github.com/user-attachments/assets/38e3148a-f5e3-4e7d-bb54-410cbc499a70)

**Comment by impworks** [comment] 2024-10-28 10:47
I came across the same issue and found a workaround on SO which worked for me.

You need to add the following line into the `Values` section in your `local.settings.json` file:

```json
"FUNCTIONS_INPROC_NET8_ENABLED": "1",
```

That being said, this clumsy hack is by no means an acceptable solution, and the issue needs a proper fix.

**Comment by surgupta-msft** [comment] 2024-10-31 23:33
Closing as duplicate of - https://github.com/Azure/azure-functions-core-tools/issues/3829. Please use that issue for tracking.

**Closed by surgupta-msft** 2024-10-31 23:33 UTC
Labels: Needs: Triage (Functions), potential-bug
